--PAQUETES
    --EXTRAS
        --ESPECIFICACIONES
CREATE OR REPLACE PACKAGE PAQ_EXTRAS IS
PROCEDURE INICIALIZAR;
PROCEDURE CONSULTAR;
PROCEDURE INSERTAR(W_OID_IN IN EXTRAS.OID_IN%TYPE,W_ASCENSOR IN EXTRAS.ASCENSOR%TYPE,W_GARAJE IN EXTRAS.GARAJE%TYPE,W_WIFI IN EXTRAS.WIFI%TYPE);
PROCEDURE ACTUALIZAR (W_OID_IN IN EXTRAS.OID_IN%TYPE,W_ASCENSOR IN EXTRAS.ASCENSOR%TYPE,W_GARAJE IN EXTRAS.GARAJE%TYPE,W_WIFI IN EXTRAS.WIFI%TYPE);
PROCEDURE ELIMINAR (W_OID_IN IN EXTRAS.OID_IN%TYPE);
END;
/ 
        --CUERPOS
CREATE OR REPLACE PACKAGE BODY PAQ_EXTRAS IS
CURSOR C IS
SELECT * FROM EXTRAS;
W_EXTRAS EXTRAS%ROWTYPE;

PROCEDURE INICIALIZAR IS
BEGIN
DELETE FROM EXTRAS;
END INICIALIZAR;

PROCEDURE CONSULTAR IS
BEGIN
OPEN C;
FETCH C INTO W_EXTRAS;
DBMS_OUTPUT.PUT_LINE(RPAD('ID INMUEBLE:', 25) ||RPAD('ASCENSOR:', 25) || RPAD('GARAJE:', 25) || RPAD('WIFI:', 25));
DBMS_OUTPUT.PUT_LINE(LPAD('-', 120, '-'));
WHILE C%FOUND LOOP
DBMS_OUTPUT.PUT_LINE(RPAD(W_EXTRAS.OID_IN, 25) || RPAD(W_EXTRAS.ASCENSOR, 25) || RPAD(W_EXTRAS.GARAJE, 25) || RPAD(W_EXTRAS.WIFI, 25));
FETCH C INTO W_EXTRAS;
END LOOP;
CLOSE C;
END CONSULTAR;

PROCEDURE INSERTAR(W_OID_IN IN EXTRAS.OID_IN%TYPE,W_ASCENSOR IN EXTRAS.ASCENSOR%TYPE,W_GARAJE IN EXTRAS.GARAJE%TYPE,W_WIFI IN EXTRAS.WIFI%TYPE) IS
BEGIN
INSERT INTO EXTRAS (OID_IN, ASCENSOR, GARAJE, WIFI) VALUES (W_OID_IN, W_ASCENSOR, W_GARAJE, W_WIFI);
SELECT * INTO W_EXTRAS FROM EXTRAS WHERE OID_IN = W_OID_IN;
IF W_EXTRAS.ASCENSOR <> W_ASCENSOR OR W_EXTRAS.GARAJE <> W_GARAJE OR W_EXTRAS.WIFI <> W_WIFI
THEN
DBMS_OUTPUT.PUT_LINE('FALLO AL INSERTAR EL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO INSERTADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO AL INSERTAR EL ELEMENTO');
ROLLBACK;
END INSERTAR;

PROCEDURE ACTUALIZAR (W_OID_IN IN EXTRAS.OID_IN%TYPE,W_ASCENSOR IN EXTRAS.ASCENSOR%TYPE,W_GARAJE IN EXTRAS.GARAJE%TYPE,W_WIFI IN EXTRAS.WIFI%TYPE) IS
BEGIN
UPDATE EXTRAS SET ASCENSOR=W_ASCENSOR WHERE OID_IN=W_OID_IN;
UPDATE EXTRAS SET GARAJE=W_GARAJE WHERE OID_IN=W_OID_IN;
UPDATE EXTRAS SET WIFI=W_WIFI WHERE OID_IN=W_OID_IN;
SELECT * INTO W_EXTRAS FROM EXTRAS WHERE OID_IN = W_OID_IN;
IF W_EXTRAS.ASCENSOR <> W_ASCENSOR OR W_EXTRAS.GARAJE <> W_GARAJE OR W_EXTRAS.WIFI <> W_WIFI
THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ACTUALIZACIÓN DEL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO ACTUALIZADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ACTUALIZACIÓN DEL ELEMENTO');
ROLLBACK;
END ACTUALIZAR;

PROCEDURE ELIMINAR (W_OID_IN IN EXTRAS.OID_IN%TYPE) IS
AUX NUMBER := 0;
BEGIN
DELETE FROM EXTRAS WHERE OID_IN = W_OID_IN;
SELECT COUNT(*) INTO AUX FROM EXTRAS WHERE OID_IN = W_OID_IN;
IF AUX <> 0 THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ELIMINACIÓN DEL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO ELIMINADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ELIMINACIÓN DEL ELEMENTO');
ROLLBACK;
END ELIMINAR;

END;
/