    --RESPUESTAS
        --CABECERA
CREATE OR REPLACE PACKAGE PAQ_RESPUESTAS IS
PROCEDURE INICIALIZAR;
PROCEDURE CONSULTAR;
PROCEDURE INSERTAR(W_TEXTO IN RESPUESTAS.TEXTO%TYPE,W_FECHA IN RESPUESTAS.FECHA%TYPE,
W_OID_US IN RESPUESTAS.OID_US%TYPE,W_OID_HF IN RESPUESTAS.OID_HF%TYPE);
PROCEDURE ACTUALIZAR (W_OID_M IN RESPUESTAS.OID_M%TYPE,W_TEXTO IN RESPUESTAS.TEXTO%TYPE,W_FECHA IN RESPUESTAS.FECHA%TYPE,
W_OID_US IN RESPUESTAS.OID_US%TYPE,W_OID_HF IN RESPUESTAS.OID_HF%TYPE);
PROCEDURE ELIMINAR (W_OID_M IN RESPUESTAS.OID_M%TYPE);
END;
/ 
        --CUERPO
create or replace PACKAGE BODY PAQ_RESPUESTAS IS
CURSOR C IS
SELECT * FROM RESPUESTAS;
W_RESPUESTAS RESPUESTAS%ROWTYPE;

PROCEDURE INICIALIZAR IS
BEGIN
DELETE FROM RESPUESTAS;
END INICIALIZAR;

PROCEDURE CONSULTAR IS
BEGIN
OPEN C;
FETCH C INTO W_RESPUESTAS;
DBMS_OUTPUT.PUT_LINE(RPAD('TEXTO:', 25) || RPAD('FECHA:', 25)|| RPAD('OID_M:', 25)|| RPAD('HILO:', 25));
DBMS_OUTPUT.PUT_LINE(LPAD('-', 120, '-'));
WHILE C%FOUND LOOP
DBMS_OUTPUT.PUT_LINE(RPAD(W_RESPUESTAS.TEXTO, 25) || RPAD(W_RESPUESTAS.FECHA, 25)|| RPAD(W_RESPUESTAS.OID_M, 25)|| RPAD(W_RESPUESTAS.OID_HF, 25));
FETCH C INTO W_RESPUESTAS;
END LOOP;
CLOSE C;
END CONSULTAR;

PROCEDURE INSERTAR(W_TEXTO IN RESPUESTAS.TEXTO%TYPE,W_FECHA IN RESPUESTAS.FECHA%TYPE, 
W_OID_US IN RESPUESTAS.OID_US%TYPE,W_OID_HF IN RESPUESTAS.OID_HF%TYPE) IS
W_OID_M RESPUESTAS.OID_M%TYPE;
BEGIN
INSERT INTO RESPUESTAS (TEXTO, FECHA, OID_US, OID_HF) VALUES (W_TEXTO, W_FECHA, W_OID_US, W_OID_HF);
W_OID_M := SEC_RESPUESTAS.CURRVAL;
SELECT * INTO W_RESPUESTAS FROM RESPUESTAS WHERE OID_M = W_OID_M;
IF W_RESPUESTAS.TEXTO != W_TEXTO OR W_RESPUESTAS.FECHA != W_FECHA OR
 W_RESPUESTAS.OID_US != W_OID_US OR W_RESPUESTAS.OID_HF != W_OID_HF 
THEN
DBMS_OUTPUT.PUT_LINE('FALLO AL INSERTAR EL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO INSERTADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO AL INSERTAR EL ELEMENTO');
ROLLBACK;
END INSERTAR;

PROCEDURE ACTUALIZAR (W_OID_M IN RESPUESTAS.OID_M%TYPE,W_TEXTO IN RESPUESTAS.TEXTO%TYPE,W_FECHA IN RESPUESTAS.FECHA%TYPE,
W_OID_US IN RESPUESTAS.OID_US%TYPE,W_OID_HF IN RESPUESTAS.OID_HF%TYPE) IS
BEGIN
UPDATE RESPUESTAS SET TEXTO=W_TEXTO WHERE OID_M=W_OID_M;
UPDATE RESPUESTAS SET FECHA=W_FECHA WHERE OID_M=W_OID_M;

UPDATE RESPUESTAS SET OID_US=W_OID_US WHERE OID_M=W_OID_M;
UPDATE RESPUESTAS SET OID_HF=W_OID_HF WHERE OID_M=W_OID_M;
SELECT * INTO W_RESPUESTAS FROM RESPUESTAS WHERE OID_M = W_OID_M;
IF W_RESPUESTAS.TEXTO != W_TEXTO OR W_RESPUESTAS.FECHA != W_FECHA OR W_RESPUESTAS.OID_US != W_OID_US OR W_RESPUESTAS.OID_HF != W_OID_HF 
THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ACTUALIZACIÓN DEL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO ACTUALIZADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ACTUALIZACIÓN DEL ELEMENTO');
ROLLBACK;
END ACTUALIZAR;

PROCEDURE ELIMINAR (W_OID_M IN RESPUESTAS.OID_M%TYPE) IS
AUX NUMBER := 0;
BEGIN
DELETE FROM RESPUESTAS WHERE OID_M = W_OID_M;
SELECT COUNT(*) INTO AUX FROM RESPUESTAS WHERE OID_M = W_OID_M;
IF AUX <> 0 THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ELIMINACIÓN DEL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO ELIMINADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ELIMINACIÓN DEL ELEMENTO');
ROLLBACK;
END ELIMINAR;

END;
