    --INFORMACIONCONTACTOEMPRESA
        --ESPECIFICACIONES
CREATE OR REPLACE PACKAGE PAQ_INFORMACIONCONTACTOEMPRESA IS
PROCEDURE INICIALIZAR;
PROCEDURE CONSULTAR;
PROCEDURE INSERTAR(W_CIF IN INFORMACIONCONTACTOEMPRESA.CIF%TYPE,W_TELEFONO IN INFORMACIONCONTACTOEMPRESA.TELEFONO%TYPE,W_CORREOELECTRONICO IN INFORMACIONCONTACTOEMPRESA.CORREOELECTRONICO%TYPE,W_FACEBOOK IN INFORMACIONCONTACTOEMPRESA.FACEBOOK%TYPE);
PROCEDURE ACTUALIZAR (W_CIF IN INFORMACIONCONTACTOEMPRESA.CIF%TYPE,W_TELEFONO IN INFORMACIONCONTACTOEMPRESA.TELEFONO%TYPE,W_CORREOELECTRONICO IN INFORMACIONCONTACTOEMPRESA.CORREOELECTRONICO%TYPE,W_FACEBOOK IN INFORMACIONCONTACTOEMPRESA.FACEBOOK%TYPE);
PROCEDURE ELIMINAR (W_CIF IN INFORMACIONCONTACTOEMPRESA.CIF%TYPE);
END;
/ 
        --CUERPOS
CREATE OR REPLACE PACKAGE BODY PAQ_INFORMACIONCONTACTOEMPRESA IS
CURSOR C IS
SELECT * FROM INFORMACIONCONTACTOEMPRESA;
W_INFORMACIONCONTACTOEMPRESA INFORMACIONCONTACTOEMPRESA%ROWTYPE;

PROCEDURE INICIALIZAR IS
BEGIN
DELETE FROM INFORMACIONCONTACTOEMPRESA;
END INICIALIZAR;

PROCEDURE CONSULTAR IS
BEGIN
OPEN C;
FETCH C INTO W_INFORMACIONCONTACTOEMPRESA;
DBMS_OUTPUT.PUT_LINE(RPAD('CIF:', 25) || RPAD('TELEFONO:', 25) || RPAD('CORREOELECTRONICO:', 25) || RPAD('FACEBOOK:', 25));
DBMS_OUTPUT.PUT_LINE(LPAD('-', 120, '-'));
WHILE C%FOUND LOOP
DBMS_OUTPUT.PUT_LINE(RPAD(W_INFORMACIONCONTACTOEMPRESA.CIF, 25) || RPAD(W_INFORMACIONCONTACTOEMPRESA.TELEFONO, 25) ||
RPAD(W_INFORMACIONCONTACTOEMPRESA.CORREOELECTRONICO, 25) || RPAD(W_INFORMACIONCONTACTOEMPRESA.FACEBOOK, 25));
FETCH C INTO W_INFORMACIONCONTACTOEMPRESA;
END LOOP;
CLOSE C;
END CONSULTAR;

PROCEDURE INSERTAR(W_CIF IN INFORMACIONCONTACTOEMPRESA.CIF%TYPE,W_TELEFONO IN INFORMACIONCONTACTOEMPRESA.TELEFONO%TYPE,
W_CORREOELECTRONICO IN INFORMACIONCONTACTOEMPRESA.CORREOELECTRONICO%TYPE,W_FACEBOOK IN INFORMACIONCONTACTOEMPRESA.FACEBOOK%TYPE) IS
BEGIN
INSERT INTO INFORMACIONCONTACTOEMPRESA (CIF, TELEFONO, CORREOELECTRONICO, FACEBOOK) VALUES (W_CIF, W_TELEFONO, W_CORREOELECTRONICO, W_FACEBOOK);
SELECT * INTO W_INFORMACIONCONTACTOEMPRESA FROM INFORMACIONCONTACTOEMPRESA WHERE CIF = W_CIF;
IF W_INFORMACIONCONTACTOEMPRESA.CIF != W_CIF OR W_INFORMACIONCONTACTOEMPRESA.TELEFONO != W_TELEFONO OR W_INFORMACIONCONTACTOEMPRESA.CORREOELECTRONICO != W_CORREOELECTRONICO OR W_INFORMACIONCONTACTOEMPRESA.FACEBOOK != W_FACEBOOK
THEN
DBMS_OUTPUT.PUT_LINE('FALLO AL INSERTAR EL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO INSERTADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO AL INSERTAR EL ELEMENTO');
ROLLBACK;
END INSERTAR;

PROCEDURE ACTUALIZAR (W_CIF IN INFORMACIONCONTACTOEMPRESA.CIF%TYPE,W_TELEFONO IN INFORMACIONCONTACTOEMPRESA.TELEFONO%TYPE,W_CORREOELECTRONICO IN INFORMACIONCONTACTOEMPRESA.CORREOELECTRONICO%TYPE,W_FACEBOOK IN INFORMACIONCONTACTOEMPRESA.FACEBOOK%TYPE) IS
BEGIN
UPDATE INFORMACIONCONTACTOEMPRESA SET CIF=W_CIF WHERE CIF=W_CIF;
UPDATE INFORMACIONCONTACTOEMPRESA SET TELEFONO=W_TELEFONO WHERE CIF=W_CIF;
UPDATE INFORMACIONCONTACTOEMPRESA SET CORREOELECTRONICO=W_CORREOELECTRONICO WHERE CIF=W_CIF;
UPDATE INFORMACIONCONTACTOEMPRESA SET FACEBOOK=W_FACEBOOK WHERE CIF=W_CIF;
SELECT * INTO W_INFORMACIONCONTACTOEMPRESA FROM INFORMACIONCONTACTOEMPRESA WHERE CIF = W_CIF;
IF W_INFORMACIONCONTACTOEMPRESA.CIF != W_CIF OR W_INFORMACIONCONTACTOEMPRESA.TELEFONO != W_TELEFONO OR W_INFORMACIONCONTACTOEMPRESA.CORREOELECTRONICO != W_CORREOELECTRONICO OR W_INFORMACIONCONTACTOEMPRESA.FACEBOOK != W_FACEBOOK
THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ACTUALIZACIÓN DEL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO ACTUALIZADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ACTUALIZACIÓN DEL ELEMENTO');
ROLLBACK;
END ACTUALIZAR;

PROCEDURE ELIMINAR (W_CIF IN INFORMACIONCONTACTOEMPRESA.CIF%TYPE) IS
AUX NUMBER := 0;
BEGIN
DELETE FROM INFORMACIONCONTACTOEMPRESA WHERE CIF = W_CIF;
SELECT COUNT(*) INTO AUX FROM INFORMACIONCONTACTOEMPRESA WHERE CIF = W_CIF;
IF AUX <> 0 THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ELIMINACIÓN DEL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO ELIMINADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ELIMINACIÓN DEL ELEMENTO');
ROLLBACK;
END ELIMINAR;

END;