--PAQUETES
    --ALQUILERES
        --ESPECIFICACIONES
CREATE OR REPLACE PACKAGE PAQ_ALQUILERES IS
PROCEDURE INICIALIZAR;
PROCEDURE CONSULTAR;
PROCEDURE INSERTAR(W_OID_IN IN ALQUILERES.OID_IN%TYPE,W_FECHA_ALQUILER IN ALQUILERES.FECHA_ALQUILER%TYPE,
W_FECHA_SALIDA IN ALQUILERES.FECHA_SALIDA%TYPE,W_OID_CO IN ALQUILERES.OID_CO%TYPE,W_OID_US IN ALQUILERES.OID_US%TYPE);
PROCEDURE ACTUALIZAR (W_OID_AL IN ALQUILERES.OID_AL%TYPE,W_OID_IN IN ALQUILERES.OID_IN%TYPE,W_FECHA_ALQUILER IN ALQUILERES.FECHA_ALQUILER%TYPE,
W_FECHA_SALIDA IN ALQUILERES.FECHA_SALIDA%TYPE,W_OID_CO IN ALQUILERES.OID_CO%TYPE,W_OID_US IN ALQUILERES.OID_US%TYPE);
PROCEDURE ELIMINAR (W_OID_AL IN ALQUILERES.OID_AL%TYPE);
END;
/ 
        --CUERPOS
CREATE OR REPLACE PACKAGE BODY PAQ_ALQUILERES IS
CURSOR C IS
SELECT * FROM ALQUILERES;
W_ALQUILERES ALQUILERES%ROWTYPE;

PROCEDURE INICIALIZAR IS
BEGIN
DELETE FROM ALQUILERES;
END INICIALIZAR;

PROCEDURE CONSULTAR IS
BEGIN
OPEN C;
FETCH C INTO W_ALQUILERES;
DBMS_OUTPUT.PUT_LINE(RPAD('ID ALQUILER:', 25) || RPAD('ID INMUEBLE:', 25) || RPAD('FECHA DE ALQUILER (ENTRADA):', 25) 
|| RPAD('FECHA DE SALIDA:', 25)|| RPAD('ID COMERCIAL:', 25)|| RPAD('ID USUARIO:', 25));
DBMS_OUTPUT.PUT_LINE(LPAD('-', 120, '-'));
WHILE C%FOUND LOOP
DBMS_OUTPUT.PUT_LINE(RPAD(W_ALQUILERES.OID_AL, 25) || RPAD(W_ALQUILERES.OID_IN, 25) || RPAD(W_ALQUILERES.FECHA_ALQUILER, 25)||
RPAD(W_ALQUILERES.FECHA_SALIDA, 25) ||RPAD(W_ALQUILERES.OID_CO, 25) ||RPAD(W_ALQUILERES.OID_US, 25));
FETCH C INTO W_ALQUILERES;
END LOOP;
CLOSE C;
END CONSULTAR;

PROCEDURE INSERTAR(W_OID_IN IN ALQUILERES.OID_IN%TYPE,W_FECHA_ALQUILER IN ALQUILERES.FECHA_ALQUILER%TYPE,
W_FECHA_SALIDA IN ALQUILERES.FECHA_SALIDA%TYPE,W_OID_CO IN ALQUILERES.OID_CO%TYPE,W_OID_US IN ALQUILERES.OID_US%TYPE) IS
W_OID_AL ALQUILERES.OID_AL%TYPE;
BEGIN
INSERT INTO ALQUILERES (OID_IN,FECHA_ALQUILER, FECHA_SALIDA, OID_CO, OID_US) VALUES (W_OID_IN, W_FECHA_ALQUILER, W_FECHA_SALIDA, W_OID_CO, W_OID_US);
W_OID_AL := SEC_ALQUILERES.CURRVAL;
SELECT * INTO W_ALQUILERES FROM ALQUILERES WHERE OID_AL = W_OID_AL;
IF W_ALQUILERES.OID_AL <> W_OID_AL OR W_ALQUILERES.OID_IN <> W_OID_IN OR W_ALQUILERES.FECHA_ALQUILER <> W_FECHA_ALQUILER OR
W_ALQUILERES.FECHA_SALIDA <> W_FECHA_SALIDA OR W_ALQUILERES.OID_CO <> W_OID_CO OR W_ALQUILERES.OID_US <> W_OID_US 
THEN
DBMS_OUTPUT.PUT_LINE('FALLO AL INSERTAR EL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO INSERTADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO AL INSERTAR EL ELEMENTO');
ROLLBACK;
END INSERTAR;

PROCEDURE ACTUALIZAR (W_OID_AL IN ALQUILERES.OID_AL%TYPE,W_OID_IN IN ALQUILERES.OID_IN%TYPE,W_FECHA_ALQUILER IN ALQUILERES.FECHA_ALQUILER%TYPE,
W_FECHA_SALIDA IN ALQUILERES.FECHA_SALIDA%TYPE,W_OID_CO IN ALQUILERES.OID_CO%TYPE,W_OID_US IN ALQUILERES.OID_US%TYPE) IS
BEGIN
UPDATE ALQUILERES SET OID_IN=W_OID_IN WHERE OID_AL=W_OID_AL;
UPDATE ALQUILERES SET FECHA_ALQUILER=W_FECHA_ALQUILER WHERE OID_AL=W_OID_AL;
UPDATE ALQUILERES SET FECHA_SALIDA=W_FECHA_SALIDA WHERE OID_AL=W_OID_AL;
UPDATE ALQUILERES SET OID_CO=W_OID_CO WHERE OID_AL=W_OID_AL;
UPDATE ALQUILERES SET OID_US=W_OID_US WHERE OID_AL=W_OID_AL;
SELECT * INTO W_ALQUILERES FROM ALQUILERES WHERE OID_AL=W_OID_AL;
IF  W_ALQUILERES.OID_AL <> W_OID_AL OR W_ALQUILERES.OID_IN <> W_OID_IN OR W_ALQUILERES.FECHA_ALQUILER <> W_FECHA_ALQUILER OR
W_ALQUILERES.FECHA_SALIDA <> W_FECHA_SALIDA OR W_ALQUILERES.OID_CO <> W_OID_CO OR W_ALQUILERES.OID_US <> W_OID_US 
THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ACTUALIZACIÓN DEL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO ACTUALIZADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ACTUALIZACIÓN DEL ELEMENTO');
ROLLBACK;
END ACTUALIZAR;

PROCEDURE ELIMINAR (W_OID_AL IN ALQUILERES.OID_AL%TYPE) IS
AUX NUMBER := 0;
BEGIN
DELETE FROM ALQUILERES WHERE OID_AL = W_OID_AL;
SELECT COUNT(*) INTO AUX FROM ALQUILERES WHERE OID_AL = W_OID_AL;
IF AUX <> 0 THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ELIMINACIÓN DEL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO ELIMINADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ELIMINACIÓN DEL ELEMENTO');
ROLLBACK;
END ELIMINAR;

END;
/