--PAQUETES
    --EXTRAS
        --ESPECIFICACIONES
CREATE OR REPLACE PACKAGE PAQ_ESTAENLISTASEG IS
PROCEDURE INICIALIZAR;
PROCEDURE CONSULTAR;
PROCEDURE INSERTAR(W_OID_IN IN ESTAENLISTASEG.OID_IN%TYPE,W_OID_US IN ESTAENLISTASEG.OID_US%TYPE);
PROCEDURE ACTUALIZAR (W_OID_ESTAENSEG IN ESTAENLISTASEG.OID_ESTAENSEG%TYPE,W_OID_IN IN ESTAENLISTASEG.OID_IN%TYPE,W_OID_US IN ESTAENLISTASEG.OID_US%TYPE);
PROCEDURE ELIMINAR (W_OID_ESTAENSEG IN ESTAENLISTASEG.OID_ESTAENSEG%TYPE);
END;
/ 
        --CUERPOS
CREATE OR REPLACE PACKAGE BODY PAQ_ESTAENLISTASEG IS
CURSOR C IS
SELECT * FROM ESTAENLISTASEG;
W_ESTAENLISTASEG ESTAENLISTASEG%ROWTYPE;

PROCEDURE INICIALIZAR IS
BEGIN
DELETE FROM ESTAENLISTASEG;
END INICIALIZAR;

PROCEDURE CONSULTAR IS
BEGIN
OPEN C;
FETCH C INTO W_ESTAENLISTASEG;
DBMS_OUTPUT.PUT_LINE(RPAD('ID ESTAENLALISTAFAV:', 25) ||RPAD('OID_IN:', 25) || RPAD('ID USUARIO:', 25));
DBMS_OUTPUT.PUT_LINE(LPAD('-', 120, '-'));
WHILE C%FOUND LOOP
DBMS_OUTPUT.PUT_LINE(RPAD(W_ESTAENLISTASEG.OID_ESTAENSEG, 25) || RPAD(W_ESTAENLISTASEG.OID_IN, 25) || RPAD(W_ESTAENLISTASEG.OID_US, 25));
FETCH C INTO W_ESTAENLISTASEG;
END LOOP;
CLOSE C;
END CONSULTAR;

PROCEDURE INSERTAR(W_OID_IN IN ESTAENLISTASEG.OID_IN%TYPE,W_OID_US IN ESTAENLISTASEG.OID_US%TYPE) IS
W_OID_ESTAENSEG ESTAENLISTASEG.OID_ESTAENSEG%TYPE;
BEGIN
INSERT INTO ESTAENLISTASEG (OID_IN, OID_US) VALUES (W_OID_IN, W_OID_US);
W_OID_ESTAENSEG := SEC_ESTAENLISTASEG.CURRVAL;
SELECT * INTO W_ESTAENLISTASEG FROM ESTAENLISTASEG WHERE OID_ESTAENSEG = W_OID_ESTAENSEG;
IF W_ESTAENLISTASEG.OID_IN <> W_OID_IN OR W_ESTAENLISTASEG.OID_US <> W_OID_US
THEN
DBMS_OUTPUT.PUT_LINE('FALLO AL INSERTAR EL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO INSERTADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO AL INSERTAR EL ELEMENTO');
ROLLBACK;
END INSERTAR;

PROCEDURE ACTUALIZAR (W_OID_ESTAENSEG IN ESTAENLISTASEG.OID_ESTAENSEG%TYPE,W_OID_IN IN ESTAENLISTASEG.OID_IN%TYPE,W_OID_US IN ESTAENLISTASEG.OID_US%TYPE) IS
BEGIN
UPDATE ESTAENLISTASEG SET OID_IN=W_OID_IN WHERE OID_ESTAENSEG=W_OID_ESTAENSEG;
UPDATE ESTAENLISTASEG SET OID_US=W_OID_US WHERE OID_ESTAENSEG=W_OID_ESTAENSEG;
SELECT * INTO W_ESTAENLISTASEG FROM ESTAENLISTASEG WHERE OID_ESTAENSEG = W_OID_ESTAENSEG;
IF W_ESTAENLISTASEG.OID_IN <> W_OID_IN OR W_ESTAENLISTASEG.OID_US <> W_OID_US
THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ACTUALIZACIÓN DEL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO ACTUALIZADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ACTUALIZACIÓN DEL ELEMENTO');
ROLLBACK;
END ACTUALIZAR;

PROCEDURE ELIMINAR (W_OID_ESTAENSEG IN ESTAENLISTASEG.OID_ESTAENSEG%TYPE) IS
AUX NUMBER := 0;
BEGIN
DELETE FROM ESTAENLISTASEG WHERE OID_ESTAENSEG = W_OID_ESTAENSEG;
SELECT COUNT(*) INTO AUX FROM ESTAENLISTASEG WHERE W_OID_ESTAENSEG = W_OID_ESTAENSEG;
IF AUX <> 0 THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ELIMINACIÓN DEL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO ELIMINADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ELIMINACIÓN DEL ELEMENTO');
ROLLBACK;
END ELIMINAR;

END;
/
