--PAQUETES
    --EXTRAS
        --ESPECIFICACIONES
CREATE OR REPLACE PACKAGE PAQ_IMAGENES IS
PROCEDURE INICIALIZAR;
PROCEDURE CONSULTAR;
PROCEDURE INSERTAR(W_OID_IN IN IMAGENES.OID_IN%TYPE);
PROCEDURE ACTUALIZAR (W_OID_IM IN IMAGENES.OID_IM%TYPE, W_OID_IN IN IMAGENES.OID_IN%TYPE);
PROCEDURE ELIMINAR (W_OID_IM IN IMAGENES.OID_IM%TYPE);
END;
/ 
        --CUERPOS
CREATE OR REPLACE PACKAGE BODY PAQ_IMAGENES IS
CURSOR C IS
SELECT * FROM IMAGENES;
W_IMAGENES IMAGENES%ROWTYPE;

PROCEDURE INICIALIZAR IS
BEGIN
DELETE FROM IMAGENES;
END INICIALIZAR;

PROCEDURE CONSULTAR IS
BEGIN
OPEN C;
FETCH C INTO W_IMAGENES;
DBMS_OUTPUT.PUT_LINE(RPAD('ID IMAGEN:', 25) || RPAD('ID INMUEBLE:', 25));
DBMS_OUTPUT.PUT_LINE(LPAD('-', 120, '-'));
WHILE C%FOUND LOOP
DBMS_OUTPUT.PUT_LINE(RPAD(W_IMAGENES.OID_IM, 25) || RPAD(W_IMAGENES.OID_IN, 25));
FETCH C INTO W_IMAGENES;
END LOOP;
CLOSE C;
END CONSULTAR;

PROCEDURE INSERTAR(W_OID_IN IN IMAGENES.OID_IN%TYPE) IS
W_OID_IM IMAGENES.OID_IM%TYPE;
BEGIN
INSERT INTO IMAGENES (OID_IN) VALUES (W_OID_IN);
W_OID_IM := SEC_IMAGENES.CURRVAL;
SELECT * INTO W_IMAGENES FROM IMAGENES WHERE OID_IM = W_OID_IM;
DBMS_OUTPUT.PUT_LINE(RPAD(W_IMAGENES.OID_IM,25)||RPAD(W_IMAGENES.OID_IN,25));
IF W_IMAGENES.OID_IN != W_OID_IN
THEN
DBMS_OUTPUT.PUT_LINE('FALLO AL INSERTAR EL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO INSERTADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO AL INSERTAR EL ELEMENTO');
ROLLBACK;
END INSERTAR;

PROCEDURE ACTUALIZAR (W_OID_IM IN IMAGENES.OID_IM%TYPE, W_OID_IN IN IMAGENES.OID_IN%TYPE) IS
BEGIN
UPDATE IMAGENES SET OID_IN=W_OID_IN WHERE OID_IM=W_OID_IM;
SELECT * INTO W_IMAGENES FROM IMAGENES WHERE OID_IN = W_OID_IN;
IF W_IMAGENES.OID_IN <> W_OID_IN
THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ACTUALIZACIÓN DEL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO ACTUALIZADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ACTUALIZACIÓN DEL ELEMENTO');
ROLLBACK;
END ACTUALIZAR;

PROCEDURE ELIMINAR (W_OID_IM IN IMAGENES.OID_IM%TYPE) IS
AUX NUMBER := 0;
BEGIN
DELETE FROM IMAGENES WHERE OID_IM = W_OID_IM;
SELECT COUNT(*) INTO AUX FROM IMAGENES WHERE OID_IM = W_OID_IM;
IF AUX <> 0 THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ELIMINACIÓN DEL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO ELIMINADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ELIMINACIÓN DEL ELEMENTO');
ROLLBACK;
END ELIMINAR;

END;
/