--PAQUETES
    --INMUEBLES
        --ESPECIFICACIONES
CREATE OR REPLACE PACKAGE PAQ_INMUEBLES IS
PROCEDURE INICIALIZAR;
PROCEDURE CONSULTAR;
PROCEDURE INSERTAR(W_DIRECCION IN INMUEBLES.DIRECCION%TYPE,W_PRECIO IN INMUEBLES.PRECIO%TYPE,W_ZONA IN INMUEBLES.ZONA%TYPE,W_METROS IN INMUEBLES.METROS%TYPE,
W_TIPOINMUEBLE IN INMUEBLES.TIPOINMUEBLE%TYPE,W_TIPOCONSTRUCCION IN INMUEBLES.TIPOCONSTRUCCION%TYPE,W_EFICIENCIAENERGETICA IN INMUEBLES.EFICIENCIAENERGETICA%TYPE,
W_HABITACIONES IN INMUEBLES.HABITACIONES%TYPE,W_BAÑOS IN INMUEBLES.BAÑOS%TYPE, W_ID_COMERCIAL IN INMUEBLES.OID_COMERCIAL%TYPE);
PROCEDURE ACTUALIZAR (W_OID_IN IN INMUEBLES.OID_IN%TYPE,W_DIRECCION IN INMUEBLES.DIRECCION%TYPE,W_PRECIO IN INMUEBLES.PRECIO%TYPE,W_ZONA IN INMUEBLES.ZONA%TYPE,W_METROS IN INMUEBLES.METROS%TYPE,
W_TIPOINMUEBLE IN INMUEBLES.TIPOINMUEBLE%TYPE,W_TIPOCONSTRUCCION IN INMUEBLES.TIPOCONSTRUCCION%TYPE,W_EFICIENCIAENERGETICA IN INMUEBLES.EFICIENCIAENERGETICA%TYPE,
W_HABITACIONES IN INMUEBLES.HABITACIONES%TYPE,W_BAÑOS IN INMUEBLES.BAÑOS%TYPE, W_ID_COMERCIAL IN INMUEBLES.OID_COMERCIAL%TYPE);
PROCEDURE ELIMINAR (W_OID_IN IN INMUEBLES.OID_IN%TYPE);
END;
/ 
        --CUERPOS
CREATE OR REPLACE PACKAGE BODY PAQ_INMUEBLES IS
CURSOR C IS
SELECT * FROM INMUEBLES;
W_INMUEBLES INMUEBLES%ROWTYPE;

PROCEDURE INICIALIZAR IS
BEGIN
DELETE FROM INMUEBLES;
END INICIALIZAR;

PROCEDURE CONSULTAR IS
BEGIN
OPEN C;
FETCH C INTO W_INMUEBLES;
DBMS_OUTPUT.PUT_LINE(RPAD('ID INMUEBLE:', 25) || RPAD('DIRECCION:', 25) || RPAD('PRECIO:', 25) || RPAD('ZONA:', 25) || RPAD('METROS CUADRADOS:', 25)||RPAD('TIPO DE INMUEBLE:', 25) 
|| RPAD('TIPO DE CONSTRUCCION:', 25) || RPAD('EFICIENCIA ENERGÉTICA:', 25) || RPAD('Nº HABITACIONES:', 25) || RPAD('Nº CUARTOS DE BAÑO:', 25)|| RPAD('COMERCIAL A CARGO', 25));
DBMS_OUTPUT.PUT_LINE(LPAD('-', 120, '-'));
WHILE C%FOUND LOOP
DBMS_OUTPUT.PUT_LINE(RPAD(W_INMUEBLES.OID_IN, 25) || RPAD(W_INMUEBLES.DIRECCION, 25) || RPAD(W_INMUEBLES.PRECIO, 25) || RPAD(W_INMUEBLES.ZONA, 25) ||
RPAD(W_INMUEBLES.METROS, 25)|| RPAD(W_INMUEBLES.TIPOINMUEBLE, 25) || RPAD(W_INMUEBLES.TIPOCONSTRUCCION, 25) || RPAD(W_INMUEBLES.EFICIENCIAENERGETICA, 25) || 
RPAD(W_INMUEBLES.HABITACIONES, 25) || RPAD(W_INMUEBLES.BAÑOS, 25) ||RPAD(W_INMUEBLES.OID_COMERCIAL, 25) );
FETCH C INTO W_INMUEBLES;
END LOOP;
CLOSE C;
END CONSULTAR;

PROCEDURE INSERTAR(W_DIRECCION IN INMUEBLES.DIRECCION%TYPE,W_PRECIO IN INMUEBLES.PRECIO%TYPE,W_ZONA IN INMUEBLES.ZONA%TYPE,W_METROS IN INMUEBLES.METROS%TYPE,
W_TIPOINMUEBLE IN INMUEBLES.TIPOINMUEBLE%TYPE,W_TIPOCONSTRUCCION IN INMUEBLES.TIPOCONSTRUCCION%TYPE,W_EFICIENCIAENERGETICA IN INMUEBLES.EFICIENCIAENERGETICA%TYPE,
W_HABITACIONES IN INMUEBLES.HABITACIONES%TYPE,W_BAÑOS IN INMUEBLES.BAÑOS%TYPE, W_ID_COMERCIAL IN INMUEBLES.OID_COMERCIAL%TYPE) IS
W_OID_IN INMUEBLES.OID_IN%TYPE;
BEGIN
INSERT INTO INMUEBLES (DIRECCION, PRECIO, ZONA, METROS, TIPOINMUEBLE, TIPOCONSTRUCCION, EFICIENCIAENERGETICA, HABITACIONES, BAÑOS, OID_COMERCIAL) 
VALUES (W_DIRECCION, W_PRECIO, W_ZONA, W_METROS, W_TIPOINMUEBLE, W_TIPOCONSTRUCCION, W_EFICIENCIAENERGETICA, W_HABITACIONES, W_BAÑOS, W_ID_COMERCIAL);
W_OID_IN := SEC_INMUEBLES.CURRVAL;
SELECT * INTO W_INMUEBLES FROM INMUEBLES WHERE OID_IN = W_OID_IN;
IF W_INMUEBLES.DIRECCION <> W_DIRECCION OR W_INMUEBLES.PRECIO <> W_PRECIO OR W_INMUEBLES.ZONA <> W_ZONA OR W_INMUEBLES.METROS <> W_METROS OR W_INMUEBLES.TIPOINMUEBLE <> W_TIPOINMUEBLE 
OR W_INMUEBLES.TIPOCONSTRUCCION <> W_TIPOCONSTRUCCION OR W_INMUEBLES.EFICIENCIAENERGETICA <> W_EFICIENCIAENERGETICA OR W_INMUEBLES.HABITACIONES <> W_HABITACIONES 
OR W_INMUEBLES.BAÑOS <> W_BAÑOS OR W_INMUEBLES.OID_COMERCIAL <> W_ID_COMERCIAL
THEN
DBMS_OUTPUT.PUT_LINE('FALLO AL INSERTAR EL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO INSERTADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO AL INSERTAR EL ELEMENTO');
ROLLBACK;
END INSERTAR;

PROCEDURE ACTUALIZAR (W_OID_IN IN INMUEBLES.OID_IN%TYPE,W_DIRECCION IN INMUEBLES.DIRECCION%TYPE,W_PRECIO IN INMUEBLES.PRECIO%TYPE,W_ZONA IN INMUEBLES.ZONA%TYPE,W_METROS IN INMUEBLES.METROS%TYPE,
W_TIPOINMUEBLE IN INMUEBLES.TIPOINMUEBLE%TYPE,W_TIPOCONSTRUCCION IN INMUEBLES.TIPOCONSTRUCCION%TYPE,W_EFICIENCIAENERGETICA IN INMUEBLES.EFICIENCIAENERGETICA%TYPE,
W_HABITACIONES IN INMUEBLES.HABITACIONES%TYPE,W_BAÑOS IN INMUEBLES.BAÑOS%TYPE, W_ID_COMERCIAL IN INMUEBLES.OID_COMERCIAL%TYPE) IS
BEGIN
UPDATE INMUEBLES SET DIRECCION=W_DIRECCION WHERE OID_IN=W_OID_IN;
UPDATE INMUEBLES SET PRECIO=W_PRECIO WHERE OID_IN=W_OID_IN;
UPDATE INMUEBLES SET ZONA=W_ZONA WHERE OID_IN=W_OID_IN;
UPDATE INMUEBLES SET METROS=W_METROS WHERE OID_IN=W_OID_IN;
UPDATE INMUEBLES SET TIPOINMUEBLE=W_TIPOINMUEBLE WHERE OID_IN=W_OID_IN;
UPDATE INMUEBLES SET TIPOCONSTRUCCION=W_TIPOCONSTRUCCION WHERE OID_IN=W_OID_IN;
UPDATE INMUEBLES SET EFICIENCIAENERGETICA=W_EFICIENCIAENERGETICA WHERE OID_IN=W_OID_IN;
UPDATE INMUEBLES SET HABITACIONES=W_HABITACIONES WHERE OID_IN=W_OID_IN;
UPDATE INMUEBLES SET BAÑOS=W_BAÑOS WHERE OID_IN=W_OID_IN;
UPDATE INMUEBLES SET OID_COMERCIAL=W_ID_COMERCIAL WHERE OID_IN=W_OID_IN;
SELECT * INTO W_INMUEBLES FROM INMUEBLES WHERE OID_IN = W_OID_IN;
IF W_INMUEBLES.DIRECCION <> W_DIRECCION OR W_INMUEBLES.PRECIO <> W_PRECIO OR W_INMUEBLES.ZONA <> W_ZONA OR W_INMUEBLES.METROS <> W_METROS OR W_INMUEBLES.TIPOINMUEBLE <> W_TIPOINMUEBLE 
OR W_INMUEBLES.TIPOCONSTRUCCION <> W_TIPOCONSTRUCCION OR W_INMUEBLES.EFICIENCIAENERGETICA <> W_EFICIENCIAENERGETICA OR W_INMUEBLES.HABITACIONES <> W_HABITACIONES 
OR W_INMUEBLES.BAÑOS <> W_BAÑOS OR W_INMUEBLES.OID_COMERCIAL <> W_ID_COMERCIAL
THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ACTUALIZACIÓN DEL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO ACTUALIZADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ACTUALIZACIÓN DEL ELEMENTO');
ROLLBACK;
END ACTUALIZAR;

PROCEDURE ELIMINAR (W_OID_IN IN INMUEBLES.OID_IN%TYPE) IS
AUX NUMBER := 0;
BEGIN
DELETE FROM INMUEBLES WHERE OID_IN = W_OID_IN;
SELECT COUNT(*) INTO AUX FROM INMUEBLES WHERE OID_IN = W_OID_IN;
IF AUX <> 0 THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ELIMINACIÓN DEL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO ELIMINADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ELIMINACIÓN DEL ELEMENTO');
ROLLBACK;
END ELIMINAR;

END;
/