--PAQUETES
--EXTRAS       
--ESPECIFICACIONES
CREATE OR REPLACE PACKAGE PAQ_NOTIFICACIONES IS
PROCEDURE INICIALIZAR;
PROCEDURE CONSULTAR;
PROCEDURE INSERTAR(W_MENSAJE IN NOTIFICACIONES.MENSAJE%TYPE, W_OID_US IN NOTIFICACIONES.OID_US%TYPE);
PROCEDURE ACTUALIZAR (W_OID_NOT IN NOTIFICACIONES.OID_NOT%TYPE, W_MENSAJE IN NOTIFICACIONES.MENSAJE%TYPE, W_OID_US IN NOTIFICACIONES.OID_US%TYPE);
PROCEDURE ELIMINAR (W_OID_NOT IN NOTIFICACIONES.OID_NOT%TYPE);
END;
/ 
    --CUERPOS
CREATE OR REPLACE PACKAGE BODY PAQ_NOTIFICACIONES IS
CURSOR C IS
SELECT * FROM NOTIFICACIONES;
W_NOTIFICACIONES NOTIFICACIONES%ROWTYPE;

PROCEDURE INICIALIZAR IS
BEGIN
DELETE FROM NOTIFICACIONES;
END INICIALIZAR;

PROCEDURE CONSULTAR IS
BEGIN
OPEN C;
FETCH C INTO W_NOTIFICACIONES;
DBMS_OUTPUT.PUT_LINE(RPAD('ID NOTIFICACION:', 25) || RPAD('MENSAJE:', 25) || RPAD('ID USUARIO:', 25));
DBMS_OUTPUT.PUT_LINE(LPAD('-', 120, '-'));
WHILE C%FOUND LOOP
DBMS_OUTPUT.PUT_LINE(RPAD(W_NOTIFICACIONES.OID_NOT, 25) || RPAD(W_NOTIFICACIONES.OID_US, 25) || RPAD(W_NOTIFICACIONES.OID_US, 25));
FETCH C INTO W_NOTIFICACIONES;
END LOOP;
CLOSE C;
END CONSULTAR;

PROCEDURE INSERTAR(W_MENSAJE IN NOTIFICACIONES.MENSAJE%TYPE, W_OID_US IN NOTIFICACIONES.OID_US%TYPE)IS
W_OID_NOT NOTIFICACIONES.OID_NOT%TYPE;
BEGIN
INSERT INTO NOTIFICACIONES (OID_NOT, MENSAJE, OID_US) VALUES (W_OID_NOT,W_MENSAJE, W_OID_US);
W_OID_NOT := SEC_NOTIFICACIONES.CURRVAL;
SELECT * INTO W_NOTIFICACIONES FROM NOTIFICACIONES WHERE OID_NOT = W_OID_NOT;
IF W_NOTIFICACIONES.MENSAJE != W_MENSAJE OR W_NOTIFICACIONES.OID_US != W_OID_US
THEN
DBMS_OUTPUT.PUT_LINE('FALLO AL INSERTAR EL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO INSERTADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO AL INSERTAR EL ELEMENTO');
ROLLBACK;
END INSERTAR;

PROCEDURE ACTUALIZAR
(W_OID_NOT IN NOTIFICACIONES.OID_NOT%TYPE, W_MENSAJE IN NOTIFICACIONES.MENSAJE%TYPE, W_OID_US IN NOTIFICACIONES.OID_US%TYPE) IS
BEGIN
UPDATE NOTIFICACIONES SET MENSAJE=W_MENSAJE WHERE OID_NOT=W_OID_NOT;
UPDATE NOTIFICACIONES SET OID_US=W_OID_US WHERE OID_NOT=W_OID_NOT;
SELECT * INTO W_NOTIFICACIONES FROM NOTIFICACIONES WHERE OID_NOT = W_OID_NOT;
IF W_NOTIFICACIONES.MENSAJE != W_MENSAJE OR W_NOTIFICACIONES.OID_US != W_OID_US
THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ACTUALIZACIÓN DEL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO ACTUALIZADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ACTUALIZACIÓN DEL ELEMENTO');
ROLLBACK;
END ACTUALIZAR;

PROCEDURE ELIMINAR (W_OID_NOT IN NOTIFICACIONES.OID_NOT%TYPE) IS
AUX NUMBER := 0;
BEGIN
DELETE FROM NOTIFICACIONES WHERE OID_NOT = W_OID_NOT;
SELECT COUNT(*) INTO AUX FROM NOTIFICACIONES WHERE OID_NOT = W_OID_NOT;
IF AUX <> 0 THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ELIMINACIÓN DEL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO ELIMINADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ELIMINACIÓN DEL ELEMENTO');
ROLLBACK;
END ELIMINAR;
END;
/