--LISTASSEGUIMIENTOS
        
--ESPECIFICACIONES

CREATE OR REPLACE PACKAGE PAQ_LISTASSEGUIMIENTO IS
PROCEDURE INICIALIZAR;
PROCEDURE CONSULTAR;
PROCEDURE INSERTAR;
PROCEDURE ELIMINAR (W_OID_SEG IN LISTASSEGUIMIENTO.OID_SEG%TYPE);
END;
/ 
   
    --CUERPOS

CREATE OR REPLACE PACKAGE BODY PAQ_LISTASSEGUIMIENTO IS
CURSOR C IS
SELECT * FROM LISTASSEGUIMIENTO;
W_LISTASSEGUIMIENTO LISTASSEGUIMIENTO%ROWTYPE;
PROCEDURE INICIALIZAR IS
BEGIN
DELETE FROM LISTASSEGUIMIENTO;
END INICIALIZAR;

PROCEDURE CONSULTAR IS
BEGIN
OPEN C;
FETCH C INTO W_LISTASSEGUIMIENTO;
DBMS_OUTPUT.PUT_LINE(RPAD('ID LISTASSEGUIMIENTO:', 25));
DBMS_OUTPUT.PUT_LINE(LPAD('-', 120, '-'));
WHILE C%FOUND LOOP
DBMS_OUTPUT.PUT_LINE(RPAD(W_LISTASSEGUIMIENTO.OID_SEG, 25));
FETCH C INTO W_LISTASSEGUIMIENTO;
END LOOP;
CLOSE C;
END CONSULTAR;

PROCEDURE INSERTAR IS
W_OID_SEG LISTASSEGUIMIENTO.OID_SEG%TYPE;
BEGIN
INSERT INTO LISTASSEGUIMIENTO(OID_SEG) VALUES ('A');
W_OID_SEG := SEC_LISTASSEGUIMIENTO.CURRVAL;
SELECT * INTO W_LISTASSEGUIMIENTO FROM LISTASSEGUIMIENTO WHERE OID_SEG = W_OID_SEG;
IF W_LISTASSEGUIMIENTO.OID_SEG != W_OID_SEG
THEN
DBMS_OUTPUT.PUT_LINE('FALLO AL INSERTAR EL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO INSERTADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO AL INSERTAR EL ELEMENTO');
ROLLBACK;
END INSERTAR;

PROCEDURE ELIMINAR (W_OID_SEG IN LISTASSEGUIMIENTO.OID_SEG%TYPE) IS
AUX NUMBER := 0;
BEGIN
DELETE FROM LISTASSEGUIMIENTO WHERE OID_SEG = W_OID_SEG;
SELECT COUNT(*) INTO AUX FROM LISTASSEGUIMIENTO WHERE OID_SEG = W_OID_SEG;
IF AUX <> 0 THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ELIMINACIÓN DEL ELEMENTO');
ELSE
DBMS_OUTPUT.PUT_LINE('ELEMENTO ELIMINADO CORRECTAMENTE');
END IF;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('FALLO EN LA ELIMINACIÓN DEL ELEMENTO');
ROLLBACK;
END ELIMINAR;
END;
/