INSERT INTO INFORMACIONCONTACTOEMPRESA(CIF,TELEFONO,CORREOELECTRONICO,FACEBOOK) VALUES ('21457898R',955904578,'inmalpiges@gmail.com','Inmobiliaria alpiges');
iNSERT INTO OFICINAS(DIRECCION,DIAS,HORA_APERTURA,HORA_CIERRE,CIF) VALUES ('Calle Inmobiliaria s/n','De lunes a viernes','09:00','12:00','214578R');

INSERT INTO COMERCIALES (OID_CO, DNI, NOMBRE, APELLIDOS, FECHA_NACIMIENTO, CORREO_ELECTRONICO, TELEFONO, DIRECCION) 
VALUES (1,'12865650W', 'Alejandro', 'Apellido', TO_DATE('1/03/1979','DD/MM/YYYY'), 'Alejandro@alpiges.com', 633257839, 'Calle Inmobiliaria s/n');
INSERT INTO COMERCIALES (OID_CO, DNI, NOMBRE, APELLIDOS, FECHA_NACIMIENTO, CORREO_ELECTRONICO, TELEFONO, DIRECCION) 
VALUES (2,'X9528615Z', 'Javier', 'Apellido', TO_DATE('16/03/1946','DD/MM/YYYY'), 'Javier@alpiges.com', 747907768, 'Calle Inmobiliaria s/n');
INSERT INTO COMERCIALES (OID_CO, DNI, NOMBRE, APELLIDOS, FECHA_NACIMIENTO, CORREO_ELECTRONICO, TELEFONO, DIRECCION) 
VALUES (3,'57038343E', 'Jorge', 'Apellido', TO_DATE('1/07/1997','DD/MM/YYYY'), 'Jorge@alpiges.com', 755866408, 'Calle Inmobiliaria s/n');
INSERT INTO COMERCIALES (OID_CO, DNI, NOMBRE, APELLIDOS, FECHA_NACIMIENTO, CORREO_ELECTRONICO, TELEFONO, DIRECCION) 
VALUES (4,'57038343C', 'Enrique', 'Apellido', TO_DATE('05/10/1968','DD/MM/YYYY'), 'Enrique@alpiges.com', 755866409, 'Calle Inmobiliaria s/n');

INSERT INTO INMUEBLES (OID_IN, DIRECCION, PRECIO, ZONA, METROS, TIPOINMUEBLE, TIPOCONSTRUCCION, EFICIENCIAENERGETICA, HABITACIONES, BA�OS, OID_COMERCIAL,ASCENSOR,GARAJE,WIFI) 
VALUES (1,'Calle Falsa 123',200000,'cascoAntiguo',120,'Adosasado','Nueva','C',5,3,1,'NO','YES','NO');
INSERT INTO INMUEBLES (OID_IN, DIRECCION, PRECIO, ZONA, METROS, TIPOINMUEBLE, TIPOCONSTRUCCION, EFICIENCIAENERGETICA, HABITACIONES, BA�OS, OID_COMERCIAL,ASCENSOR,GARAJE,WIFI) 
VALUES (2,'Calle Evergreen Terrace 74',300000,'elValle',120,'Adosasado','Antigua','B',7,2,2,'YES','YES','NO');
INSERT INTO INMUEBLES (OID_IN, DIRECCION, PRECIO, ZONA, METROS, TIPOINMUEBLE, TIPOCONSTRUCCION, EFICIENCIAENERGETICA, HABITACIONES, BA�OS, OID_COMERCIAL,ASCENSOR,GARAJE,WIFI) 
VALUES (3,'Fondo de Bikini 3',400000,'lasMoreras',30,'Oficina','Reforma','C',4,3,3,'YES','YES','NO');
INSERT INTO INMUEBLES (OID_IN, DIRECCION, PRECIO, ZONA, METROS, TIPOINMUEBLE, TIPOCONSTRUCCION, EFICIENCIAENERGETICA, HABITACIONES, BA�OS, OID_COMERCIAL,ASCENSOR,GARAJE,WIFI) 
VALUES (4,'Kame House s/n',500000,'Los laZarzuela',500,'Oficina','Nueva','B',2,1,4,'YES','YES','NO');
INSERT INTO INMUEBLES (OID_IN, DIRECCION, PRECIO, ZONA, METROS, TIPOINMUEBLE, TIPOCONSTRUCCION, EFICIENCIAENERGETICA, HABITACIONES, BA�OS, OID_COMERCIAL,ASCENSOR,GARAJE,WIFI) 
VALUES (5,'Facultad de Informatica s/n',200000,'cascoAntiguo',120,'Adosasado','Nueva','C',5,3,1,'NO','YES','NO');
