SET SERVEROUTPUT ON;

--ALQUILERES
BEGIN
PAQ_ALQUILERES.INICIALIZAR;
PAQ_ALQUILERES.INSERTAR(1,TO_DATE('16/03/1945 12:00','DD/MM/YYYY HH:MI'), TO_DATE('16/03/1946 12:00','DD/MM/YYYY HH:MI'),1,3);
PAQ_ALQUILERES.INSERTAR(2,TO_DATE('12/05/1990 12:00','DD/MM/YYYY HH:MI'), TO_DATE('12/05/1991 12:00','DD/MM/YYYY HH:MI'),3,3);
PAQ_ALQUILERES.INSERTAR(3,TO_DATE('05/10/1967 12:00','DD/MM/YYYY HH:MI'), TO_DATE('05/10/1968 12:00','DD/MM/YYYY HH:MI'),3,1);
PAQ_ALQUILERES.INSERTAR(3,TO_DATE('07/12/1963 12:00','DD/MM/YYYY HH:MI'), TO_DATE('07/12/1964 12:00','DD/MM/YYYY HH:MI'),3,3);
DBMS_OUTPUT.PUT_LINE('INSERTAR ALQUILER CON FECHA DE SALIDA ANTERIOR A FECHA ALQUILER:');
PAQ_ALQUILERES.INSERTAR(1,TO_DATE('17/03/1930','DD/MM/YYYY HH:MI'), TO_DATE('17/04/1920 12:00','DD/MM/YYYY HH:MI'),1,1);

DBMS_OUTPUT.PUT_LINE('INSERTAR ALQUILER INCUMPLIENDO LA RN 002:');
PAQ_ALQUILERES.INSERTAR(1,TO_DATE('04/09/1901','DD/MM/YYYY '), TO_DATE('09/09/1901 ','DD/MM/YYYY '),1,1);

DBMS_OUTPUT.PUT_LINE('INSERTAR ALQUILER CON FECHA DE ENTRADA NULA:');
PAQ_ALQUILERES.INSERTAR(1,TO_DATE('17/11/1923','DD/MM/YYYY HH:MI'), NULL,1,3);
DBMS_OUTPUT.PUT_LINE('INSERTAR ALQUILER CON COMERCIAL NULO:');
PAQ_ALQUILERES.INSERTAR(1,TO_DATE('11/03/1913','DD/MM/YYYY HH:MI'), TO_DATE('11/03/1914 12:00','DD/MM/YYYY HH:MI'),NULL,3);
DBMS_OUTPUT.PUT_LINE('INSERTAR ALQUILER INCUMPLIENDO LA RN 004:');
PAQ_ALQUILERES.INSERTAR(5,TO_DATE('01/03/2015 09:00','DD/MM/YYYY HH:MI'), TO_DATE('01/04/2018 12:00','DD/MM/YYYY HH:MI'),3,3);
DBMS_OUTPUT.PUT_LINE('INSERTAR ALQUILER INCUMPLIENDO LA RN 005:');
PAQ_ALQUILERES.INSERTAR(5,TO_DATE('01/03/1922','DD/MM/YYYY HH:MI'), TO_DATE('01/04/1922 12:00','DD/MM/YYYY HH:MI'),3,3);
PAQ_ALQUILERES.ELIMINAR(3);
PAQ_ALQUILERES.CONSULTAR;
END;
/

--COMERCIALES
BEGIN
PAQ_COMERCIALES.INICIALIZAR;
PAQ_COMERCIALES.INSERTAR('12865650W', 'Azan�as', 'Echevarr�a', TO_DATE('16/03/1945','DD/MM/YYYY'), 'Azanias@gustr.com', 633257839, 'Calle Coronado 1', 'YES');
PAQ_COMERCIALES.INSERTAR('X9528615Z', 'N�lida', 'Villa', TO_DATE('16/03/1946','DD/MM/YYYY'), 'Nelida@superrito.com', 747907768, 'Calle Falsa 123', 'YES');
PAQ_COMERCIALES.INSERTAR('57038343E', 'Pompilio', 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), 'Pompilio@gustr.com', 755866408, 'Calle Coronado 1', 'YES');
PAQ_COMERCIALES.INSERTAR('57038343C', 'Alejandro', 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), 'ale@gustr.com', 755866409, 'Calle Coronado 1', 'YES');
DBMS_OUTPUT.PUT_LINE('INSERTAR COMERCIAL SIN PRIVILEGIO');
PAQ_COMERCIALES.INSERTAR('12865650W', 'Azan�as', 'Echevarr�a', TO_DATE('16/03/1945','DD/MM/YYYY'), 'Azanias@gustr.com', 633257839, 'Calle Coronado 1', 'NO');
DBMS_OUTPUT.PUT_LINE('INSERTAR COMERCIAL CON ALGUNA VARIABLE NULA');
PAQ_COMERCIALES.INSERTAR( NULL, 'Pompilio', 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), 'Pompilio@gustr.com', 755866408, 'Calle Coronado 1', 'YES');
PAQ_COMERCIALES.INSERTAR('55212476X', NULL, 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), 'Pompilio@gustr.com', 755866408, 'Calle Coronado 1', 'YES');
PAQ_COMERCIALES.INSERTAR('55212476X', 'Pompilio', NULL, TO_DATE('05/10/1968','DD/MM/YYYY'), 'Pompilio@gustr.com', 755866408, 'Calle Coronado 1', 'YES');
PAQ_COMERCIALES.INSERTAR('55212476X', 'Pompilio', 'Cano', NULL, 'PompilioCanoBallesteros@gustr.com', 755866408, 'Calle Coronado 1', 'YES');
PAQ_COMERCIALES.INSERTAR('55212476X', 'Pompilio', 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), NULL, 755866408, 'Calle Coronado 1', 'YES');
PAQ_COMERCIALES.INSERTAR('55212476X', 'Pompilio', 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), 'Pompilio@gustr.com', NULL, 'Calle Coronado 1', 'YES');
PAQ_COMERCIALES.INSERTAR('55212476X', 'Pompilio', 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), 'Pompilio@gustr.com', 755866408, NULL, 'YES');
DBMS_OUTPUT.PUT_LINE('INSERTAR COMERCIAL CON DNI DUPLICADO');
PAQ_COMERCIALES.INSERTAR('12865650W', 'Pompilio', 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), 'Pompilio@gustr.com', 755866408, 'Calle Coronado 1', 'YES');
DBMS_OUTPUT.PUT_LINE('INSERTAR COMERCIAL CON CORREO ELECTRONICO DUPLICADO');
PAQ_COMERCIALES.INSERTAR('55212476X', 'Pompilio', 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), 'Nelida@superrito.com', 755866408, 'Calle Coronado 1', 'YES');
DBMS_OUTPUT.PUT_LINE('INSERTAR COMERCIAL CON TELEFONO DUPLICADO');
PAQ_COMERCIALES.INSERTAR('55212476X', 'Pompilio', 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), 'Pompilio@gustr.com', 755866408, 'Calle Coronado 1', 'YES');
DBMS_OUTPUT.PUT_LINE('ACTUALIZAR UN COMERCIAL NO EXISTENTE');
PAQ_COMERCIALES.ACTUALIZAR(59, '57038343E', 'Pompilio', 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), 'Pompilio@gustr.com', 755866408, 'Calle Coronado 1', 'YES');
PAQ_COMERCIALES.ELIMINAR(4);
PAQ_COMERCIALES.CONSULTAR;
END;
/

--ESTAENLISTAFAV
BEGIN
PAQ_ESTAENLISTAFAV.INICIALIZAR;
PAQ_ESTAENLISTAFAV.INSERTAR(1,1);
PAQ_ESTAENLISTAFAV.INSERTAR(2,2);
DBMS_OUTPUT.PUT_LINE('INSERTAR ESTAENLISTAFAV CON LISTA DE FAVORITOS NULA:');
PAQ_ESTAENLISTAFAV.INSERTAR(3,NULL);
PAQ_ESTAENLISTAFAV.ACTUALIZAR(2,2,1);
DBMS_OUTPUT.PUT_LINE('ACTUALIZAR ESTAENLISTAFAV CON INMUEBLE NULO:');
PAQ_ESTAENLISTAFAV.ACTUALIZAR(1,NULL,3);
PAQ_ESTAENLISTAFAV.ELIMINAR(2);
PAQ_ESTAENLISTAFAV.CONSULTAR;
END;
/

--ESTAENLISTASEG
BEGIN
PAQ_ESTAENLISTASEG.INICIALIZAR;
PAQ_ESTAENLISTASEG.INSERTAR(1,3);
PAQ_ESTAENLISTASEG.INSERTAR(2,1);
DBMS_OUTPUT.PUT_LINE('INSERTAR ESTAENLISTASEG CON LISTA DE FAVORITOS NULA:');
PAQ_ESTAENLISTASEG.INSERTAR(3,NULL);
PAQ_ESTAENLISTASEG.ACTUALIZAR(2,2,2);
DBMS_OUTPUT.PUT_LINE('ACTUALIZAR ESTAENLISTASEG CON INMUEBLE NULO:');
PAQ_ESTAENLISTASEG.ACTUALIZAR(1,NULL,3);
PAQ_ESTAENLISTASEG.ELIMINAR(3);
PAQ_ESTAENLISTASEG.CONSULTAR;
END;
/

--EXTRAS
BEGIN
PAQ_EXTRAS.INICIALIZAR;
PAQ_EXTRAS.INSERTAR(1,'YES','YES','NO');
PAQ_EXTRAS.INSERTAR(2,'YES',NULL,'NO');
PAQ_EXTRAS.INSERTAR(3,'YES','NO','NO');
PAQ_EXTRAS.ACTUALIZAR(3,'YES','YES','YES');
DBMS_OUTPUT.PUT_LINE('ACTUALIZAR EXTRAS ESTABLECIENDO CON WIFI NO VALIDO:');
PAQ_EXTRAS.ACTUALIZAR(3,'YES','YES','TAL VEZ');
PAQ_EXTRAS.ELIMINAR(3);
PAQ_EXTRAS.CONSULTAR;
END;
/

--HILOSFORO
BEGIN
PAQ_HILOSFORO.INICIALIZAR;
PAQ_HILOSFORO.INSERTAR('Cuantos ba�os tiene esta casa?','Necesito saber cuantos ba�os tiene esta casa',TO_DATE('17/03/1930','DD/MM/YYYY'),1,NULL);
PAQ_HILOSFORO.INSERTAR('Cuantas habitaciones tiene esta casa?','Necesito saber cuantas habitaciones tiene esta casa',TO_DATE('17/03/2000','DD/MM/YYYY'),3,NULL);
PAQ_HILOSFORO.INSERTAR('Donde esta situada esta casa?','Necesito saber donde esta situada esta casa',TO_DATE('20/07/2018','DD/MM/YYYY'),NULL,1);
PAQ_HILOSFORO.INSERTAR('Cuantos a�os tiene esta construccion?','Necesito saber cuantos a�os tiene esta construccion',TO_DATE('17/03/1930','DD/MM/YYYY'),NULL,1);
DBMS_OUTPUT.PUT_LINE('INSERTAR TITULO NULO:');
PAQ_HILOSFORO.INSERTAR(NULL,'Necesito saber cuantos ba�os tiene esta casa',TO_DATE('17/03/1930','DD/MM/YYYY'),2,NULL);
DBMS_OUTPUT.PUT_LINE('INSERTAR DESCRIPCION NULA:');
PAQ_HILOSFORO.INSERTAR('Cuantos ba�os tiene esta casa?',NULL,TO_DATE('17/03/1930','DD/MM/YYYY'),NULL,1);
DBMS_OUTPUT.PUT_LINE('INSERTAR HILO INCVUMPLIENDO LA RN 003');
PAQ_HILOSFORO.INSERTAR('Cuantos ba�os tiene esta casa?',NULL,TO_DATE('17/03/1930','DD/MM/YYYY'),NULL,59);
PAQ_HILOSFORO.ACTUALIZAR('Cuantos ba�os tiene esta casa?','Necesito saber cuantos ba�os tiene esta casa en la direccion tal',TO_DATE('17/03/1930','DD/MM/YYYY'),2,NULL);
PAQ_HILOSFORO.ELIMINAR('Cuantos ba�os tiene esta casa?');
PAQ_HILOSFORO.CONSULTAR;
END;
/

--HISTORIALESBUSQUEDA
BEGIN
PAQ_HISTORIALESBUSQUEDA.INICIALIZAR;
PAQ_HISTORIALESBUSQUEDA.INSERTAR(TO_DATE('16/03/1945','DD/MM/YYYY'), 1, NULL, 1);
PAQ_HISTORIALESBUSQUEDA.INSERTAR(TO_DATE('16/03/1946','DD/MM/YYYY'), 2, 3, NULL);
PAQ_HISTORIALESBUSQUEDA.INSERTAR(TO_DATE('05/10/1968','DD/MM/YYYY'), 3, 3, NULL);
DBMS_OUTPUT.PUT_LINE('INSERTAR HISTORIAL CON ALGUNA VARIABLE NULA');
PAQ_HISTORIALESBUSQUEDA.INSERTAR(NULL, 3, 3, NULL);
PAQ_HISTORIALESBUSQUEDA.INSERTAR(TO_DATE('05/10/1968','DD/MM/YYYY'), NULL, 3, NULL);
PAQ_HISTORIALESBUSQUEDA.INSERTAR(TO_DATE('05/10/1968','DD/MM/YYYY'), 3, NULL, NULL);
PAQ_HISTORIALESBUSQUEDA.ACTUALIZAR(2,TO_DATE('05/12/1969','DD/MM/YYYY'), 3, 1, NULL);
PAQ_HISTORIALESBUSQUEDA.ELIMINAR(3);
PAQ_HISTORIALESBUSQUEDA.CONSULTAR;
END;
/

--IMAGENES
BEGIN
PAQ_IMAGENES.INICIALIZAR;
PAQ_IMAGENES.INSERTAR(1);
PAQ_IMAGENES.INSERTAR(2);
PAQ_IMAGENES.INSERTAR(3);
DBMS_OUTPUT.PUT_LINE('ACTUALIZAR IMAGEN ESTABLECIENDO EL INMUEBLE RESPECTIVO NULO:');
PAQ_IMAGENES.ACTUALIZAR(2,NULL);
PAQ_IMAGENES.ELIMINAR(3);
PAQ_IMAGENES.CONSULTAR;
END;
/

--INFORMACIONCONTACTOEMPRESA
BEGIN
PAQ_INFORMACIONCONTACTOEMPRESA.INICIALIZAR;
PAQ_INFORMACIONCONTACTOEMPRESA.INSERTAR('21457898R',955855728,'inmalpiges@gmail.com','Inmobiliaria alpiges');
PAQ_INFORMACIONCONTACTOEMPRESA.INSERTAR('12345678A',955920252,'inmalpiges@gmail.com','Inmobiliaria alpiges');
DBMS_OUTPUT.PUT_LINE('INSERTAR CIF NULO:');
PAQ_INFORMACIONCONTACTOEMPRESA.INSERTAR(NULL,955785578,'inmalpiges@gmail.com','Inmobiliaria alpiges');
DBMS_OUTPUT.PUT_LINE('INSERTAR TELEFONO NULO:');
PAQ_INFORMACIONCONTACTOEMPRESA.INSERTAR('21457898R',NULL,'inmalpiges@gmail.com','Inmobiliaria alpiges');
PAQ_INFORMACIONCONTACTOEMPRESA.ACTUALIZAR('21457898R',685899525,'inmalpiges@gmail.com','Inmobiliaria alpiges');
DBMS_OUTPUT.PUT_LINE('ACTUALIZAR CORREO A NULO:');
PAQ_INFORMACIONCONTACTOEMPRESA.ACTUALIZAR('21457898R',68258995,NULL,'Inmobiliaria alpiges');
PAQ_INFORMACIONCONTACTOEMPRESA.ELIMINAR('12345678A');
PAQ_INFORMACIONCONTACTOEMPRESA.CONSULTAR;
END;
/

--INMUEBLES
BEGIN
PAQ_INMUEBLES.INICIALIZAR;
PAQ_INMUEBLES.INSERTAR('Calle Verdadera 1',200000,'Springfield',120,'Adosasado','Nueva','C',5,3,3);
PAQ_INMUEBLES.INSERTAR('Evergreen Terrace 74',300000,'Springfield',120,'Adosasado','Antigua','B',7,2,1);
PAQ_INMUEBLES.INSERTAR('Calle  Verg�enza 4',400000,'Murcia',30,'Oficina','Reforma','C',4,3,2);
PAQ_INMUEBLES.INSERTAR('Calle Selaboca 3',500000,'Los Maquinas',500,'Oficina','Nueva','B',2,1,1);
DBMS_OUTPUT.PUT_LINE('INSERTAR INMUEBLE CON N� HABITACIONES NULO:');
PAQ_INMUEBLES.INSERTAR('Calle CepeCalvo 10',200000,'Springfield',120,'Adosasado','Nueva','D',NULL,8,2);
DBMS_OUTPUT.PUT_LINE('INSERTAR INMUEBLE CON TIPOINMUEBLE NO VALIDO:');
PAQ_INMUEBLES.INSERTAR('Calle Cienaga 45',1000,'El Bosque M�gico',80,'Casa','Nueva','E',4,6,2);
DBMS_OUTPUT.PUT_LINE('INSERTAR INMUEBLE CON PRECIO NEGATIVO:');
PAQ_INMUEBLES.INSERTAR('Calle Chimuelo 4',-200000000,'El Cielo',220,'Chalet','Antigua','A',5,3,2);
DBMS_OUTPUT.PUT_LINE('INSERTAR INMUEBLE CON TIPOCONSTRUCCION NO VALIDO:');
PAQ_INMUEBLES.INSERTAR('Calle QVEF 5',200000,'Malasa�a',120,'Adosasado','No muy nueva','C',3,3,2);
PAQ_INMUEBLES.ACTUALIZAR(1,'Calle Falsa 123',200000,'Springfield',120,'Adosasado','Nueva','B',5,2,3);
PAQ_INMUEBLES.ACTUALIZAR(2,'Calle Despacito 2',200000,'Fonsi',120,'Adosasado','Nueva','D',44,3,1);
PAQ_INMUEBLES.ACTUALIZAR(3,'Paseo Al Perro 56',200000,'La Calle',120,'Adosasado','Nueva','C',5,3,2);
DBMS_OUTPUT.PUT_LINE('ACTUALIZAR INMUEBLE INCUMPLIENDO LA RN 001:');
PAQ_INMUEBLES.ACTUALIZAR(1,'Calle Falsa 123',200000,'Springfield',120,'Adosasado','Nueva','B',5,2,NULL);
DBMS_OUTPUT.PUT_LINE('ACTUALIZAR INMUEBLE CON METROS CUADRADOS NEGATIVOS:');
PAQ_INMUEBLES.ACTUALIZAR(2,'Calle Despacito 2',200000,'Fonsi',-120,'Adosasado','Nueva','D',44,3,1);
DBMS_OUTPUT.PUT_LINE('INSERTAR INMUEBLE CON ZONA NULA:');
PAQ_INMUEBLES.ACTUALIZAR(3,'Paseo Al Perro 56',200000,NULL,120,'Adosasado','Nueva','C',5,3,3);
PAQ_INMUEBLES.ELIMINAR(4);
PAQ_INMUEBLES.CONSULTAR;
END;
/

--LISTASFAVORITOS
BEGIN
PAQ_LISTASFAVORITOS.INICIALIZAR;
PAQ_LISTASFAVORITOS.INSERTAR;
PAQ_LISTASFAVORITOS.INSERTAR;
PAQ_LISTASFAVORITOS.INSERTAR;
PAQ_LISTASFAVORITOS.INSERTAR;
PAQ_LISTASFAVORITOS.ELIMINAR(4);
PAQ_LISTASFAVORITOS.CONSULTAR;
END;
/

--LISTASSEGUIMIENTO
BEGIN
PAQ_LISTASSEGUIMIENTO.INICIALIZAR;
PAQ_LISTASSEGUIMIENTO.INSERTAR;
PAQ_LISTASSEGUIMIENTO.INSERTAR;
PAQ_LISTASSEGUIMIENTO.INSERTAR;
PAQ_LISTASSEGUIMIENTO.INSERTAR;
PAQ_LISTASSEGUIMIENTO.ELIMINAR(4);
PAQ_LISTASSEGUIMIENTO.CONSULTAR;
END;
/

--NOTIFICACIONES
BEGIN
PAQ_NOTIFICACIONES.INICIALIZAR;
PAQ_NOTIFICACIONES.INSERTAR('TIENES UN NUEVO MENSAJE', 1);
PAQ_NOTIFICACIONES.INSERTAR('NUEVOS ALOJAMIENTOS DISPONIBLES', 3 );
PAQ_NOTIFICACIONES.INSERTAR('TIENES UNA SOLICITUD DISPONIBLE', 3 );
DBMS_OUTPUT.PUT_LINE('INSERTAR ELEMENTO CON MENSAJE NULO');
PAQ_NOTIFICACIONES.INSERTAR(NULL, 4 );
PAQ_NOTIFICACIONES.ACTUALIZAR(1,'EL PAGO HA SIDO REALIZADO', 3 );
PAQ_NOTIFICACIONES.ELIMINAR(2);
PAQ_NOTIFICACIONES.CONSULTAR;
END;
/

--OFICINAS
BEGIN
PAQ_OFICINAS.INICIALIZAR;
PAQ_OFICINAS.INSERTAR('Calle calle 22','De lunes a viernes',TO_DATE('09:00','HH:MI'),TO_DATE('12:00','HH:MI'),'21457898R');
PAQ_OFICINAS.INSERTAR('Calle calle 1','De lunes a viernes',TO_DATE('09:00','HH:MI'),TO_DATE('12:00','HH:MI'),'21457898R');
PAQ_OFICINAS.INSERTAR('Calle Falsa 123','De lunes a viernes',TO_DATE('09:00','HH:MI'),TO_DATE('12:00','HH:MI'),'21457898R');
DBMS_OUTPUT.PUT_LINE('INSERTAR DIRECCION NULA:');
PAQ_OFICINAS.INSERTAR(NULL,'De lunes a viernes',TO_DATE('09:00','HH:MI'),TO_DATE('12:00','HH:MI'),'21457898R');
DBMS_OUTPUT.PUT_LINE('INSERTAR DIAS NULO:');
PAQ_OFICINAS.INSERTAR('Calle calle 22',NULL,TO_DATE('09:00','HH:MI'),TO_DATE('12:00','HH:MI'),'21457898R');
PAQ_OFICINAS.ACTUALIZAR('Calle calle 22','De martes a jueves',TO_DATE('09:00','HH:MI'),TO_DATE('12:00','HH:MI'),'21457898R');
DBMS_OUTPUT.PUT_LINE('ACTUALIZAR DIRECCION HORA_APERTURA A NULO:');
PAQ_OFICINAS.ACTUALIZAR('Calle calle 9','De lunes a viernes',NULL,TO_DATE('12:00','HH:MI'),'21457898R');
PAQ_OFICINAS.ELIMINAR('Calle calle 22');
PAQ_OFICINAS.CONSULTAR;
END;
/ 

--RESERVAS
BEGIN
PAQ_RESERVAS.INICIALIZAR;
PAQ_RESERVAS.INSERTAR(1, 1);
PAQ_RESERVAS.INSERTAR(2, 1);
PAQ_RESERVAS.INSERTAR(3, 1);
DBMS_OUTPUT.PUT_LINE('INSERTAR RESERVA CON OID_AL NULO');
PAQ_RESERVAS.INSERTAR(3,NULL);
PAQ_RESERVAS.ACTUALIZAR(2,1, 3);
DBMS_OUTPUT.PUT_LINE('ACTUALIZAR RESERVA CON OID_AL NO �NICO');
PAQ_RESERVAS.ACTUALIZAR(1,2, 3);
PAQ_RESERVAS.ELIMINAR(2);
PAQ_RESERVAS.CONSULTAR;
END;
/

--RESPUESTA
BEGIN
PAQ_RESPUESTAS.INICIALIZAR;
PAQ_RESPUESTAS.INSERTAR('Tiene 4 ba�os',TO_DATE('17/03/1930','DD/MM/YYYY'),3,NULL,'Donde esta situada esta casa?');
PAQ_RESPUESTAS.INSERTAR('Tiene 3 ba�os',TO_DATE('17/03/2000','DD/MM/YYYY'),NULL,1,'Donde esta situada esta casa?');
DBMS_OUTPUT.PUT_LINE('INSERTAR FECHA NULA:');
PAQ_RESPUESTAS.INSERTAR('Tiene 4 ba�os',NULL,3,NULL,'Cuantos ba�os tiene esta casa?');
DBMS_OUTPUT.PUT_LINE('INSERTAR TEXTO NULO:');
PAQ_RESPUESTAS.INSERTAR(NULL,TO_DATE('17/03/1930','DD/MM/YYYY'),3,NULL,'Cuantos ba�os tiene esta casa?');
PAQ_RESPUESTAS.ACTUALIZAR(1,'Tiene 4 ba�os',TO_DATE('17/03/1930','DD/MM/YYYY'),3,NULL,'Cuantos ba�os tiene esta casa?');
DBMS_OUTPUT.PUT_LINE('ACTUALIZAR RESPUESTA COMPROBANDO LA RN 003:');
PAQ_RESPUESTAS.ACTUALIZAR(2,'Tiene 4 ba�os',TO_DATE('17/03/1930','DD/MM/YYYY'),150,NULL,'Cuantos ba�os tiene esta casa?');
DBMS_OUTPUT.PUT_LINE('ACTUALIZAR RESPUESTA COMPROBANDO LA RN 003:');
PAQ_RESPUESTAS.ACTUALIZAR(2,'Tiene 4 ba�os',TO_DATE('17/03/1930','DD/MM/YYYY'),NULL,86,'Cuantos ba�os tiene esta casa?');
PAQ_RESPUESTAS.ELIMINAR('000544');
PAQ_RESPUESTAS.CONSULTAR;
END;
/

--USUARIOS
BEGIN
PAQ_USUARIOS.INICIALIZAR;
PAQ_USUARIOS.INSERTAR('12865650W', 'Azan�as', 'Echevarr�a', TO_DATE('16/03/1945','DD/MM/YYYY'), 'Azanias@gustr.com', 633257839, 'NO',1,1);
PAQ_USUARIOS.INSERTAR('X9528615Z', 'N�lida', 'Villa', TO_DATE('16/03/1946','DD/MM/YYYY'), 'Nelida@superrito.com', 747907768, 'NO',2,2);
PAQ_USUARIOS.INSERTAR('57038343E', 'Pompilio', 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), 'Pompilio@gustr.com', 755866408, 'NO',3,3);
DBMS_OUTPUT.PUT_LINE('INSERTAR USUARIO CON PRIVILEGIO');
PAQ_USUARIOS.INSERTAR('2865650W', 'Azan�as', 'Echevarr�a', TO_DATE('16/03/1945','DD/MM/YYYY'), 'Azanias@gustr.com', 633257839, 'YES',1,1);
DBMS_OUTPUT.PUT_LINE('INSERTAR USUARIO CON ALGUNA VARIABLE NULA');
PAQ_USUARIOS.INSERTAR(NULL, 'Pompilio', 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), 'Pompilio@gustr.com', 755866408, 'NO',3,3);
PAQ_USUARIOS.INSERTAR('5212476X', 'Pompilio', 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), NULL, 755866408, 'NO',3,3);
PAQ_USUARIOS.INSERTAR('5212476X', 'Pompilio', 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), 'Pompilio@gustr.com', NULL, 'NO',3,3);
PAQ_USUARIOS.INSERTAR('5212476X', 'Pompilio', 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), 'Pompilio@gustr.com', 755866408, 'NO',3,3);
DBMS_OUTPUT.PUT_LINE('INSERTAR USUARIO CON DNI DUPLICADO');
PAQ_USUARIOS.INSERTAR('2865650W', 'Pompilio', 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), 'Pompilio@gustr.com', 755866408, 'NO',3,3);
DBMS_OUTPUT.PUT_LINE('INSERTAR USUARIO CON CORREO ELECTRONICO DUPLICADO');
PAQ_USUARIOS.INSERTAR('5212476X', 'Pompilio', 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), 'Nelida@superrito.com', 755866408, 'NO',3,3);
DBMS_OUTPUT.PUT_LINE('INSERTAR USUARIO CON TELEFONO DUPLICADO');
PAQ_USUARIOS.INSERTAR('5212476X', 'Pompilio', 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), 'Pompilio@gustr.com', 755866408, 'NO',3,3);
PAQ_USUARIOS.ACTUALIZAR(3, '57038343E', 'Juan', 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), 'Pompilio@gmail.com', 666666666, 'NO',3,3);
DBMS_OUTPUT.PUT_LINE('ACTUALIZAR UN USUARIO NO EXISTENTE');
PAQ_USUARIOS.ACTUALIZAR(50, '7038343E', 'Pompilio', 'Cano', TO_DATE('05/10/1968','DD/MM/YYYY'), 'Pompilio@gustr.com', 755866408, 'NO',3,3);
PAQ_USUARIOS.ELIMINAR(2);
PAQ_USUARIOS.CONSULTAR;
END;
/

--VENTAS
BEGIN
PAQ_VENTAS.INICIALIZAR;
PAQ_VENTAS.INSERTAR(1,TO_DATE('16/03/1945','DD/MM/YYYY'), 1,3);
PAQ_VENTAS.INSERTAR(2,TO_DATE('12/05/1990','DD/MM/YYYY'), 2,3);
DBMS_OUTPUT.PUT_LINE('INSERTAR VENTA CON FECHA NULA:');
PAQ_VENTAS.INSERTAR(3,NULL,2,3);
DBMS_OUTPUT.PUT_LINE('INSERTAR VENTA CON COMERCIAL NULO:');
PAQ_VENTAS.INSERTAR(3,TO_DATE('11/03/1913','DD/MM/YYYY'), NULL,3);
PAQ_VENTAS.INSERTAR(3,TO_DATE('05/10/1967','DD/MM/YYYY'), 3,1);
PAQ_VENTAS.ACTUALIZAR(1,1,TO_DATE('03/10/1988','DD/MM/YYYY'), 1,3);
PAQ_VENTAS.ACTUALIZAR(2,2,TO_DATE('10/09/1992','DD/MM/YYYY'), 2,3);
PAQ_VENTAS.ACTUALIZAR(3,3,TO_DATE('10/04/1945','DD/MM/YYYY'), 3,1);
PAQ_VENTAS.ELIMINAR(3);
PAQ_VENTAS.CONSULTAR;
END;
/