SET SERVEROUTPUT ON;

--RF 001
EXEC PR_BUSCADORR('Calle Falsa 123');
--RF 002
EXEC PR_FILTRAR_NUM_HAB(3);
--RF 003
EXEC PR_FILTRAR_NUM_BAÑOS(3);
--RF 004
EXEC PR_FILTRAR_ZONA('El Bosque Mágico');
--RF 005
EXEC PR_FILTRAR_PRECIO (200000);
--RF 006
EXEC PR_FILTRAR_METROS(80);
--RF 007
EXEC PR_FILTRAR_TIPO_INM('Oficina');
--RF 008
EXEC PR_FILTRAR_TIPOCONSTRUCCION('Reforma')
--RF 009
EXEC PR_FILTRAR_EFICIENCIA('C')
--RF 010
EXEC PR_FILTRAR_EXTRAS('YES','YES','NO')
--RF 011
EXEC INSERTARINMUEBLEFAVORITOS(1,2)
--RF 012
EXEC INSERTARINMUEBLESEGUIMIENTO(2,1)
--RF 013
EXEC PR_NOTIFICAR(2,'La base de datos de virus ha sido actualizada');
--RF 014
EXEC PR_CREAR_HILOS_FORO('¿Qué piso debo elegir?', 'Echadme una mano anda', TO_DATE('19/04/1965 12:00','DD/MM/YYYY HH:MI'),1,NULL);
--RF 015
EXEC PR_RESPONDER_HILOS_FORO ('Ese está muy bien',TO_DATE('19/04/1965 18:30','DD/MM/YYYY HH:MM'),NULL,2,'¿Qué piso debo elegir?');
--RF 016
EXEC PR_BORRAR_RESPUESTA (2, 2);
--RF 017
EXEC PR_BORRAR_RESPUESTA_COMERCIAL (1, 1);
--RF 018
EXEC PR_CAMBIAR_DESCRIPCION ('¿Qué piso debo elegir?','Necesito ayuda');
--RF 019
EXEC PR_CREAR_PERFIL_INMUEBLE ('Calle La Pantomima',30000,'El Canutillo',500,'Oficina','Reforma','A',1,1);
--RF 020
EXEC PR_ACTUALIZAR_INMUEBLE (5,'Avenida La Rassa',30000,'El Canutillo',500,'Oficina','Reforma','A',1,1);;
--RF 021
EXEC PR_ANADIR_IMAGEN(2);
--RF 022
EXEC PR_ACTUALIZAR_COMERCIAL_INMUEBLE(3,1);
--RF 023
EXEC PR_ACTUALIZAR_NOMBRE_APELLIDOS(2,'Benito','Camela');
--RF 024
EXEC PR_ACTUALIZAR_CORREO_TLF(3,'lmao@pump.it','80085707');
--RF 025
EXEC PR_ANADIR_A_LISTAFAV(1,2,3);
EXEC PR_ANADIR_A_LISTASEG(3,2,1);
EXEC PR_ELIMINAR_DE_LISTAFAV(2,3);
EXEC PR_ELIMINAR_DE_LISTASEG(2,1);

