CREATE TABLE ALQUILERES(	
    OID_AL VARCHAR2(20 BYTE) NOT NULL, 
	OID_IN VARCHAR2(20 BYTE) NOT NULL, 
	FECHA_ALQUILER DATE NOT NULL, 
    FECHA_SALIDA DATE NOT NULL,
    OID_CO VARCHAR2(20) NOT NULL,
    OID_US VARCHAR2(20) NOT NULL,
    PRIMARY KEY (OID_AL),
    FOREIGN KEY (OID_CO) REFERENCES COMERCIALES,
    FOREIGN KEY (OID_US) REFERENCES USUARIOS,
    FOREIGN KEY (OID_IN)REFERENCES INMUEBLES, 
    CONSTRAINT FECHAS CHECK (FECHA_ALQUILER<FECHA_SALIDA)
   );

CREATE TABLE COMERCIALES(
    OID_CO VARCHAR2(20) NOT NULL,
    DNI VARCHAR2(9) NOT NULL UNIQUE,
    NOMBRE VARCHAR2(20) NOT NULL,
    APELLIDOS VARCHAR2(30) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    CORREO_ELECTRONICO VARCHAR2(30) NOT NULL UNIQUE,
    TELEFONO NUMBER NOT NULL UNIQUE,
    DIRECCION VARCHAR2(20) NOT NULL,
    PRIMARY KEY (OID_CO),
    FOREIGN KEY (DIRECCION) REFERENCES OFICINAS
);

CREATE TABLE ESTAENLISTAFAV(
    OID_ESTAENFAV VARCHAR2(20) NOT NULL,
    OID_IN VARCHAR2 (20) NOT NULL,
    OID_US VARCHAR2 (20) NOT NULL,
    PRIMARY KEY (OID_ESTAENFAV),
	FOREIGN KEY (OID_IN) REFERENCES INMUEBLES,
    FOREIGN KEY (OID_US) REFERENCES USUARIOS
);

CREATE TABLE ESTAENLISTASEG(
    OID_ESTAENSEG VARCHAR2(20) NOT NULL,
    OID_IN VARCHAR2 (20) NOT NULL,
    OID_US VARCHAR2 (20) NOT NULL,
    PRIMARY KEY (OID_ESTAENSEG),
	FOREIGN KEY (OID_IN) REFERENCES INMUEBLES,
    FOREIGN KEY (OID_US) REFERENCES USUARIOS
);

CREATE TABLE HILOSFORO(
	OID_HF VARCHAR(100) NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR2(4000) NOT NULL,
    FECHA DATE NOT NULL,
    OID_US VARCHAR2(20),
    PRIMARY KEY (OID_HF),
    FOREIGN KEY (OID_US) REFERENCES USUARIOS
    );


CREATE TABLE HISTORIALESBUSQUEDA(
    FECHAYHORA DATE NOT NULL,
    OID_HB VARCHAR2(20) NOT NULL,
    OID_IN VARCHAR2(20) NOT NULL,
    OID_US VARCHAR2(20 BYTE),
    PRIMARY KEY(FECHAYHORA,OID_IN,OID_HB),
    FOREIGN KEY (OID_IN) REFERENCES INMUEBLES,
    FOREIGN KEY (OID_US) REFERENCES USUARIOS
);

CREATE TABLE IMAGENES(
     OID_IM VARCHAR2(20 BYTE) NOT NULL,
     OID_IN VARCHAR2(20 BYTE) NOT NULL,
     PRIMARY KEY (OID_IM),
     FOREIGN KEY (OID_IN) REFERENCES INMUEBLES
);

CREATE TABLE INFORMACIONCONTACTOEMPRESA(
    CIF VARCHAR2(9) NOT NULL,
    TELEFONO NUMBER NOT NULL ,
    CORREOELECTRONICO VARCHAR2(20) NOT NULL,
    FACEBOOK VARCHAR2(20) NOT NULL,
    PRIMARY KEY (CIF)    
    );

CREATE TABLE INMUEBLES(
    OID_IN VARCHAR2(20 BYTE) NOT NULL, 
	DIRECCION VARCHAR2(20 BYTE) NOT NULL UNIQUE, 
	PRECIO NUMBER NOT NULL CHECK (PRECIO>0), 
	ZONA VARCHAR2(20 BYTE) NOT NULL, 
	METROS NUMBER NOT NULL CHECK (METROS>0), 
	TIPOINMUEBLE VARCHAR2(25), 
	TIPOCONSTRUCCION VARCHAR2(25) , 
	EFICIENCIAENERGETICA VARCHAR2(25) ,
	HABITACIONES NUMBER NOT NULL CHECK (HABITACIONES>0), 
	BAÑOS NUMBER NOT NULL CHECK (BAÑOS>0), 
    OID_COMERCIAL VARCHAR2(2) NOT NULL,
	WIFI VARCHAR2(3 BYTE), 
	GARAJE VARCHAR2(3 BYTE), 
	ASCENSOR VARCHAR2(3 BYTE), 
    CONSTRAINT CONS_WI CHECK (WIFI IN ('YES','NO')), 
    CONSTRAINT CONS_GA CHECK (GARAJE IN ('YES','NO')), 
    CONSTRAINT CONS_AS CHECK (ASCENSOR IN ('YES','NO')),
    PRIMARY KEY (OID_IN),
    FOREIGN KEY (OID_COMERCIAL) REFERENCES COMERCIALES ON DELETE SET NULL,
    CONSTRAINT CONS_TI CHECK (TIPOINMUEBLE IN ('Chalet','Adosasado','Local Comercial','Oficina','Edificio','Nave Industrial','Terreno','Finca Rústica')),
    CONSTRAINT CONS_TC CHECK (TIPOCONSTRUCCION IN ('Nueva','Antigua','Reforma')),
    CONSTRAINT CONS_EF CHECK (EFICIENCIAENERGETICA IN ('A','B','C','D','E','F'))
    );

CREATE TABLE NOTIFICACIONES(
    OID_NOT VARCHAR2(20) NOT NULL,
    MENSAJE VARCHAR2(140) NOT NULL,
    OID_US VARCHAR2(20 BYTE) NOT NULL,
    PRIMARY KEY (OID_NOT),
    FOREIGN KEY (OID_US) REFERENCES USUARIOS ON DELETE CASCADE
);    

CREATE TABLE OFICINAS(
    DIRECCION VARCHAR2(20) NOT NULL,
    DIAS VARCHAR2(20) NOT NULL,
    HORA_APERTURA TIMESTAMP NOT NULL,
    HORA_CIERRE TIMESTAMP NOT NULL,
    CIF VARCHAR2(9) NOT NULL,
    PRIMARY KEY (DIRECCION),
    FOREIGN KEY (CIF) REFERENCES INFORMACIONCONTACTOEMPRESA
    );

CREATE TABLE RESERVAS(
	OID_RES VARCHAR2 (20 BYTE) NOT NULL,
    OID_AL VARCHAR2 (20 BYTE) NOT NULL UNIQUE,
    OID_US VARCHAR2(20 BYTE) NOT NULL,
	PRIMARY KEY (OID_RES),
    FOREIGN KEY (OID_AL) REFERENCES ALQUILERES ON DELETE SET NULL,
    FOREIGN KEY (OID_US) REFERENCES USUARIOS ON DELETE SET NULL
	);

CREATE TABLE RESPUESTAS(
	OID_HF VARCHAR(100) NOT NULL,
    OID_M NUMBER NOT NULL,
    TEXTO VARCHAR2(4000) NOT NULL,
    FECHA DATE NOT NULL,    
    OID_US VARCHAR2(20),
    PRIMARY KEY (OID_M),
    FOREIGN KEY (OID_US) REFERENCES USUARIOS,
    FOREIGN KEY (OID_HF) REFERENCES HILOSFORO
    );
    
CREATE TABLE USUARIOS(
    OID_US VARCHAR2(20) NOT NULL,
    DNI VARCHAR2(9) NOT NULL UNIQUE,
    NOMBRE VARCHAR2(20),
    APELLIDOS VARCHAR2(30),
    FECHA_NACIMIENTO DATE,
    CORREO_ELECTRONICO VARCHAR2(30) NOT NULL UNIQUE,
    TELEFONO NUMBER NOT NULL UNIQUE,
    CONTRASENA VARCHAR2(20) NOT NULL,
    PRIMARY KEY (OID_US)
);
   
CREATE TABLE VENTAS(
    OID_VE VARCHAR2(20 BYTE) NOT NULL, 
    OID_IN VARCHAR2(20 BYTE) NOT NULL UNIQUE, 
	FECHA_VENTA DATE NOT NULL, 
    OID_CO VARCHAR2(20) NOT NULL,
    OID_US VARCHAR2(20) NOT NULL,
    PRIMARY KEY (OID_VE),    
    FOREIGN KEY (OID_CO) REFERENCES COMERCIALES,
    FOREIGN KEY (OID_US) REFERENCES USUARIOS,
    FOREIGN KEY (OID_IN) REFERENCES INMUEBLES
   );
