+---RN 001	
CREATE OR REPLACE TRIGGER TR_ASIGNACION_DEL_AGENTE
BEFORE INSERT OR UPDATE ON INMUEBLES 
FOR EACH ROW
BEGIN
IF (:NEW.OID_COMERCIAL = NULL) THEN
RAISE_APPLICATION_ERROR (-20000, 'El inmueble debe tener un comercial a su cargo');
END IF;
END;
/

--RN 002
CREATE OR REPLACE TRIGGER TR_PERIODO_MINIMO
BEFORE INSERT OR UPDATE ON ALQUILERES 
FOR EACH ROW
DECLARE
DIAS NUMBER;
BEGIN
SELECT TRUNC(:NEW.FECHA_SALIDA) - TRUNC(:NEW.FECHA_ALQUILER) DAYS  INTO DIAS FROM DUAL;
IF (DIAS=5) THEN
RAISE_APPLICATION_ERROR (-20009, 'El periodo mínimo de alquiler es de 1 noche.');
END IF;
END;
/

--RN 003
CREATE OR REPLACE TRIGGER TR_ORGANIZACION_HILO_US
BEFORE INSERT OR UPDATE ON HILOSFORO 
FOR EACH ROW
DECLARE
CONT NUMBER;
CONT2 NUMBER;
BEGIN
SELECT COUNT(*) INTO CONT FROM USUARIOS WHERE OID_US=:NEW.OID_US;
SELECT COUNT(*) INTO CONT2 FROM COMERCIALES WHERE OID_CO=:NEW.OID_CO;
IF (CONT =0 AND CONT2=0)
THEN
RAISE_APPLICATION_ERROR(-20100, 'ESTE USUSARIO NO ESTA REGISTRADO');
END IF;
END;
/

CREATE OR REPLACE TRIGGER TR_ORGANIZACION_RESPUESTA_US
BEFORE INSERT OR UPDATE ON RESPUESTAS
FOR EACH ROW
DECLARE
CONT NUMBER;
CONT2 NUMBER;
BEGIN
SELECT COUNT(*) INTO CONT FROM USUARIOS WHERE OID_US=:NEW.OID_US;
SELECT COUNT(*) INTO CONT2 FROM COMERCIALES WHERE OID_CO=:NEW.OID_CO;
IF (CONT =0 AND CONT2=0)
THEN
RAISE_APPLICATION_ERROR(-20001, 'ESTE USUSARIO NO ESTA REGISTRADO, POR LO TANTO NO PUEDE HACER NINGUNA ACCION EN EL FORO');
END IF;
END;
/

--RN 004
CREATE OR REPLACE TRIGGER TR_ENTRADA_SALIDA_ALQUILER
AFTER INSERT OR UPDATE ON ALQUILERES
FOR EACH ROW
BEGIN
IF TO_DATE(TO_CHAR(:NEW.FECHA_ALQUILER, 'HH:MI'),'HH:MI')<=TO_DATE('11:00','HH24:MI') OR
TO_DATE(TO_CHAR(:NEW.FECHA_SALIDA, 'HH:MI'),'HH:MI')>=TO_DATE('13:00','HH24:MI')
THEN
RAISE_APPLICATION_ERROR(-20041, 'ESTE USUSARIO NO A CUMPLIDO EL REQUISITO DE ENTRADA/SALIDA DEL INMUEBLE ALQUILADO');
END IF;
END;
/

--RN 005
CREATE OR REPLACE TRIGGER TR_NOSOLAPAMIENTO
BEFORE INSERT ON ALQUILERES
FOR EACH ROW
DECLARE
CONT NUMBER;
BEGIN
SELECT COUNT(*) INTO CONT FROM ALQUILERES WHERE OID_IN=:NEW.OID_IN AND ((FECHA_ALQUILER<:NEW.FECHA_ALQUILER AND FECHA_SALIDA>:NEW.FECHA_ALQUILER) OR (FECHA_ALQUILER<:NEW.FECHA_SALIDA AND FECHA_SALIDA>:NEW.FECHA_SALIDA));
IF CONT<>0
THEN 
RAISE_APPLICATION_ERROR(-20000, 'NO SE PUEDE ALQUILAR EL INMUEBLE '||:NEW.OID_IN||' ENTRE LAS FECHAS '||:NEW.FECHA_ALQUILER||' Y '||:NEW.FECHA_SALIDA||' PORQUE YA SE ENCUENTRA ALQUILADO');
END IF;
END;