CREATE OR REPLACE TRIGGER TR_SEC_ALQUILERES
BEFORE INSERT ON ALQUILERES
FOR EACH ROW
DECLARE
VALSEC NUMBER := 0;
BEGIN
SELECT SEC_ALQUILERES.NEXTVAL INTO VALSEC FROM DUAL;
:NEW.OID_AL := VALSEC;
END;
/

CREATE OR REPLACE TRIGGER TR_SEC_COMERCIALES
BEFORE INSERT ON COMERCIALES
FOR EACH ROW
DECLARE
VALSEC NUMBER := 0;
BEGIN
SELECT SEC_COMERCIALES.NEXTVAL INTO VALSEC FROM DUAL;
:NEW.OID_CO := VALSEC;
END;
/

CREATE OR REPLACE TRIGGER TR_SEC_ESTAENLISTAFAV
BEFORE INSERT ON ESTAENLISTAFAV
FOR EACH ROW
DECLARE
VALSEC NUMBER := 0;
BEGIN
SELECT SEC_ESTAENLISTAFAV.NEXTVAL INTO VALSEC FROM DUAL;
:NEW.OID_ESTAENFAV := VALSEC;
END;
/

CREATE OR REPLACE TRIGGER TR_SEC_ESTAENLISTASEG
BEFORE INSERT ON ESTAENLISTASEG
FOR EACH ROW
DECLARE
VALSEC NUMBER := 0;
BEGIN
SELECT SEC_ESTAENLISTASEG.NEXTVAL INTO VALSEC FROM DUAL;
:NEW.OID_ESTAENSEG := VALSEC;
END;
/

CREATE OR REPLACE TRIGGER TR_SEC_HILOSFORO
BEFORE INSERT ON HILOSFORO
FOR EACH ROW
DECLARE
VALSEC NUMBER := 0;
BEGIN
SELECT SEC_HILOSFORO.NEXTVAL INTO VALSEC FROM DUAL;
:NEW.OID_HF := VALSEC;
END;
/

CREATE OR REPLACE TRIGGER TR_SEC_HISTORIALESBUSQUEDA
BEFORE INSERT ON HISTORIALESBUSQUEDA
FOR EACH ROW
DECLARE
VALSEC NUMBER := 0;
BEGIN
SELECT SEC_HISTORIALESBUSQUEDA.NEXTVAL INTO VALSEC FROM DUAL;
:NEW.OID_HB := VALSEC;
END;
/

CREATE OR REPLACE TRIGGER TR_SEC_IMAGENES
BEFORE INSERT ON IMAGENES
FOR EACH ROW
DECLARE
VALSEC NUMBER := 0;
BEGIN
SELECT SEC_IMAGENES.NEXTVAL INTO VALSEC FROM DUAL;
:NEW.OID_IM := VALSEC;
END;
/

CREATE OR REPLACE TRIGGER TR_SEC_INMUEBLES
BEFORE INSERT ON INMUEBLES
FOR EACH ROW
DECLARE
VALSEC NUMBER := 0;
BEGIN
SELECT SEC_INMUEBLES.NEXTVAL INTO VALSEC FROM DUAL;
:NEW.OID_IN := VALSEC;
END;
/

CREATE OR REPLACE TRIGGER TR_SEC_NOTIFICACIONES
BEFORE INSERT ON NOTIFICACIONES
FOR EACH ROW
DECLARE
VALSEC NUMBER := 0;
BEGIN
SELECT SEC_NOTIFICACIONES.NEXTVAL INTO VALSEC FROM DUAL;
:NEW.OID_NOT := VALSEC;
END;
/

CREATE OR REPLACE TRIGGER TR_SEC_RESERVAS
BEFORE INSERT ON RESERVAS
FOR EACH ROW
DECLARE
VALSEC NUMBER := 0;
BEGIN
SELECT SEC_RESERVAS.NEXTVAL INTO VALSEC FROM DUAL;
:NEW.OID_RES := VALSEC;
END;
/

CREATE OR REPLACE TRIGGER TR_SEC_RESPUESTAS
BEFORE INSERT ON RESPUESTAS
FOR EACH ROW
DECLARE
VALSEC NUMBER := 0;
BEGIN
SELECT SEC_RESPUESTAS.NEXTVAL INTO VALSEC FROM DUAL;
:NEW.OID_M := VALSEC;
END;
/

CREATE OR REPLACE TRIGGER TR_SEC_USUARIOS
BEFORE INSERT ON USUARIOS
FOR EACH ROW
DECLARE
VALSEC NUMBER := 0;
BEGIN
SELECT SEC_USUARIOS.NEXTVAL INTO VALSEC FROM DUAL;
:NEW.OID_US := VALSEC;
END;
/

CREATE OR REPLACE TRIGGER TR_SEC_VENTAS
BEFORE INSERT ON VENTAS
FOR EACH ROW
DECLARE
VALSEC NUMBER := 0;
BEGIN
SELECT SEC_VENTAS.NEXTVAL INTO VALSEC FROM DUAL;
:NEW.OID_VE := VALSEC;
END;
/